export const words = [
    {word: "Bundesrepublik Deutschland", fos: "", def: "[Federal Republic of Germany]"},
    {word: "schwarz", fos: "", def: "[black]"},
    {word: "rot", fos: "", def: "[red]"},
    {word: "gold", fos: "", def: "[gold]"},
    {word: "Österreich", fos: "", def: "[Austria]"},
    {word: "Ost", fos: "", def: "[East]"},
    {word: "Öst", fos: "", def: "[Abbreviation for East or Austria (Österreich)]"},
    {word: "Reich", fos: "", def: "[Empire, realm]"},
    {word: "Schweiz", fos: "", def: "[Switzerland]"},
    {word: "Land", fos: "", def: "[country, land]"},
    {word: "richtig", fos: "", def: "[correct, right]"},
    {word: "falsch", fos: "", def: "[wrong, false]"},
    {word: "Hochdeutsch", fos: "", def: "[Standard German]"},
    {word: "hoch", fos: "", def: "[high, tall]"},
    {word: "Hallo!", fos: "", def: "[Hello!] (General)"},
    {word: "Servus!", fos: "", def: "[Hello! / Goodbye!] (Bavaria, Austria)"},
    {word: "Grüß Gott!", fos: "", def: "[Hello!] (Southern Germany, Austria)"},
    {word: "Grüezi!", fos: "", def: "[Hello!] (Switzerland)"},
    {word: "Guten Morgen", fos: "", def: "[Good morning] (General)"},
    {word: "Guten Tag", fos: "", def: "[Good afternoon / Good day] (General)"},
    {word: "Guten Abend", fos: "", def: "[Good evening] (General)"},
    {word: "Tschüss!", fos: "", def: "[Bye!] (General)"},
    {word: "Auf Wiedersehen!", fos: "", def: "[Goodbye!] (General)"},
    {word: "Auf Wiederluge!", fos: "", def: "[Goodbye!] (Switzerland - usually uf Wiederluege)"},
    {word: "auf", fos: "", def: "[on, upon]"},
    {word: "in", fos: "", def: "[in, into]"},
    {word: "das", fos: "", def: "[the] (neutral), [that/this]"},
    {word: "Joghurt", fos: "", def: "[yogurt]"},
    {word: "ja", fos: "", def: "[yes]"},
    {word: "nein", fos: "", def: "[no]"},
    {word: "Vater", fos: "", def: "[father]"},
    {word: "Wagen", fos: "", def: "[car, wagon]"},
    {word: "Taxi", fos: "", def: "[taxi]"},
    {word: "Bruder", fos: "", def: "[brother]"},
    {word: "Gast", fos: "", def: "[guest]"},
    {word: "Haus", fos: "", def: "[house]"},
    {word: "Herbst", fos: "", def: "[autumn, fall]"},
    {word: "Tag", fos: "", def: "[day]"},
    {word: "Sonne", fos: "", def: "[sun]"},
    {word: "Sohn", fos: "", def: "[son]"},
    {word: "Dach", fos: "", def: "[roof]"},
    {word: "Stadt", fos: "", def: "[city]"},
    {word: "Zoo", fos: "", def: "[zoo]"},
    {word: "Zahl", fos: "", def: "[number]"},
    {word: "Gemeinschaft", fos: "", def: "[community]"},
    {word: "Ananas", fos: "", def: "[pineapple]"},
    {word: "Glas", fos: "", def: "[glass]"},
    {word: "Elefant", fos: "", def: "[elephant]"},
    {word: "Weg", fos: "", def: "[way, path]"},
    {word: "Fenster", fos: "", def: "[window]"},
    {word: "Blume", fos: "", def: "[flower]"},
    {word: "Insel", fos: "", def: "[island]"},
    {word: "Musik", fos: "", def: "[music]"},
    {word: "Brille", fos: "", def: "[glasses]"},
    {word: "Ohr", fos: "", def: "[ear]"},
    {word: "Brot", fos: "", def: "[bread]"},
    {word: "Uhr", fos: "", def: "[clock, watch, o'clock]"},
    {word: "Fuß", fos: "", def: "[foot]"},
    {word: "Mutter", fos: "", def: "[mother]"},
    {word: "Äpfel", fos: "", def: "[apples] (Plural form of Apfel)"},
    {word: "Käse", fos: "", def: "[cheese]"},
    {word: "Getränk", fos: "", def: "[drink, beverage]"},
    {word: "Öl", fos: "", def: "[oil]"},
    {word: "König", fos: "", def: "[king]"},
    {word: "Löffel", fos: "", def: "[spoon]"},
    {word: "Tür", fos: "", def: "[door]"},
    {word: "Schüler", fos: "", def: "[student, pupil] (Male)"},
    {word: "Eis", fos: "", def: "[ice, ice cream]"},
    {word: "Mai", fos: "", def: "[May] (Month)"},
    {word: "Haydn", fos: "", def: "[Haydn] (Famous composer)"},
    {word: "reisen", fos: "", def: "[to travel]"},
    {word: "Loreley", fos: "", def: "[Lorelei] (Famous rock on the Rhine)"},
    {word: "Auto", fos: "", def: "[car]"},
    {word: "Audi", fos: "", def: "[Audi] (Car brand)"},
    {word: "Bäume", fos: "", def: "[trees] (Plural form of Baum)"},
    {word: "Häuser", fos: "", def: "[houses] (Plural form of Haus)"},
    {word: "Euro", fos: "", def: "[Euro] (Currency)"},
    {word: "Zwiebeln", fos: "", def: "[onions] (Plural form of Zwiebel)"},
    {word: "Brief", fos: "", def: "[letter]"},
    {word: "Mann", fos: "", def: "[man, husband]"},
    {word: "Straße", fos: "", def: "[street]"},
    {word: "Fahrrad", fos: "", def: "[bicycle]"},
    {word: "Arzt", fos: "", def: "[doctor] (Male)"},
    {word: "Erdgeschoss", fos: "", def: "[ground floor]"},
    {word: "erst", fos: "", def: "[first, only]"},
    {word: "werden", fos: "", def: "[to become, will] (Auxiliary)"},
    {word: "Mond", fos: "", def: "[moon]"},
    {word: "Obst", fos: "", def: "[fruit]"},
    {word: "Ostern", fos: "", def: "[Easter]"},
    {word: "Buch", fos: "", def: "[book]"},
    {word: "Geburtstag", fos: "", def: "[birthday]"},
    {word: "suchen", fos: "", def: "[to search, to look for]"},
    {word: "besuchen", fos: "", def: "[to visit]"},
    {word: "Bett", fos: "", def: "[bed]"},
    {word: "immer", fos: "", def: "[always]"},
    {word: "kommen", fos: "", def: "[to come]"},
    {word: "Butter", fos: "", def: "[butter]"},
    {word: "Apfel", fos: "", def: "[apple]"},
    {word: "Ecke", fos: "", def: "[corner]"},
    {word: "Tisch", fos: "", def: "[table]"},
    {word: "Post", fos: "", def: "[mail, post office]"},
    {word: "Hunger", fos: "", def: "[hunger]"},
    {word: "Beruf", fos: "", def: "[profession, job]"},
    {word: "Idee", fos: "", def: "[idea]"},
    {word: "Student", fos: "", def: "[university student] (Male)"},
    {word: "woher", fos: "", def: "[where from]"},
    {word: "träumen", fos: "", def: "[to dream]"},
    {word: "Freund", fos: "", def: "[friend] (Male)"},
    {word: "Bäckerei", fos: "", def: "[bakery]"},
    {word: "Klavier", fos: "", def: "[piano]"},
    {word: "Baum", fos: "", def: "[tree]"},
    {word: "Clown", fos: "", def: "[clown]"},
    {word: "Delfin", fos: "", def: "[dolphin]"},
    {word: "Fisch", fos: "", def: "[fish]"},
    {word: "Giraffe", fos: "", def: "[giraffe]"},
    {word: "Huhn", fos: "", def: "[chicken]"},
    {word: "Känguru", fos: "", def: "[kangaroo]"},
    {word: "Löwe", fos: "", def: "[lion]"},
    {word: "Maus", fos: "", def: "[mouse]"},
    {word: "Nashorn", fos: "", def: "[rhinoceros]"},
    {word: "Pinguin", fos: "", def: "[penguin]"},
    {word: "Qualle", fos: "", def: "[jellyfish]"},
    {word: "Rakete", fos: "", def: "[rocket]"},
    {word: "Trommel", fos: "", def: "[drum]"},
    {word: "Vulkan", fos: "", def: "[volcano]"},
    {word: "Wal", fos: "", def: "[whale]"},
    {word: "Xylofon", fos: "", def: "[xylophone]"},
    {word: "Zebra", fos: "", def: "[zebra]"},
    {word: "sechs", fos: "", def: "[six]"},
    {word: "Fuchs", fos: "", def: "[fox]"},
    {word: "Bäcker", fos: "", def: "[baker]"},
    {word: "Glück", fos: "", def: "[luck, happiness]"},
    {word: "Viel Glück!", fos: "", def: "[Good luck!]"},
    {word: "Katze", fos: "", def: "[cat]"},
    {word: "Theater", fos: "", def: "[theater]"},
    {word: "singen", fos: "", def: "[to sing]"},
    {word: "Bank", fos: "", def: "[bank, bench]"},
    {word: "Kopf", fos: "", def: "[head]"},
    {word: "Schule", fos: "", def: "[school]"},
    {word: "machen", fos: "", def: "[to do, to make]"},
    {word: "Fluss", fos: "", def: "[river]"},
    {word: "Bauch", fos: "", def: "[stomach, belly]"},
    {word: "doch", fos: "", def: "[but, however, yes (answering negative question)]"},
    {word: "rechts", fos: "", def: "[right (direction)]"},
    {word: "Milch", fos: "", def: "[milk]"},
    {word: "Bücher", fos: "", def: "[books] (Plural form of Buch)"},
    {word: "Chance", fos: "", def: "[chance, opportunity]"},
    {word: "Chef", fos: "", def: "[boss, manager]"},
    {word: "Chaos", fos: "", def: "[chaos]"},
    {word: "Christ", fos: "", def: "[Christian] (Person)"},
    {word: "Sport", fos: "", def: "[sports]"},
    {word: "Spiel", fos: "", def: "[game]"},
    {word: "Bibliothek", fos: "", def: "[library]"},
    {word: "Programm", fos: "", def: "[program]"},
    {word: "wenig", fos: "", def: "[little, few]"},
    {word: "noch einmal", fos: "", def: "[once more, again]"},
    {word: "Vorname", fos: "", def: "[first name]"},
    {word: "Nachname", fos: "", def: "[last name]"},
    {word: "Familienname", fos: "", def: "[family name, last name]"},
    {word: "wohnen", fos: "", def: "[to live, to reside]"},
    {word: "heißen", fos: "", def: "[to be called, to be named]"},
    {word: "arbeiten", fos: "", def: "[to work]"},
    {word: "tanzen", fos: "", def: "[to dance]"},
    {word: "sein", fos: "", def: "[to be] (Auxiliary)"},
    {word: "haben", fos: "", def: "[to have] (Auxiliary)"},
    {word: "hier", fos: "", def: "[here]"},
    {word: "viel", fos: "", def: "[much, a lot]"},
    {word: "warten", fos: "", def: "[to wait]"},
    {word: "Schülerinnen", fos: "", def: "[students, pupils] (Female Plural)"},
    {word: "der", fos: "", def: "[the] (feminine Dative)"},
    {word: "dem", fos: "", def: "[the] (masculine/neutral Dative)"},
    {word: "den", fos: "", def: "[the] (plural Dative)"},
    {word: "aus", fos: "", def: "[from, out of]"},
    {word: "Italien", fos: "", def: "[Italy]"},
    {word: "Spanien", fos: "", def: "[Spain]"},
    {word: "Madrid", fos: "", def: "[Madrid]"},
    {word: "Rom", fos: "", def: "[Rome]"},
    {word: "Wien", fos: "", def: "[Vienna]"},
    {word: "Hauptstadt", fos: "", def: "[capital city]"},
    {word: "England", fos: "", def: "[England]"},
    {word: "Frankreich", fos: "", def: "[France]"},
    {word: "China", fos: "", def: "[China]"},
    {word: "Japan", fos: "", def: "[Japan]"},
    {word: "Paris", fos: "", def: "[Paris]"},
    {word: "Peking", fos: "", def: "[Beijing]"},
    {word: "London", fos: "", def: "[London]"},
    {word: "Tokio", fos: "", def: "[Tokyo]"},
    {word: "Bern", fos: "", def: "[Bern]"},
    {word: "gehen", fos: "", def: "[to go, to walk]"},
    {word: "lernen", fos: "", def: "[to learn, to study]"},
    {word: "trinken", fos: "", def: "[to drink]"},
    {word: "sagen", fos: "", def: "[to say, to tell]"},
    {word: "kennen", fos: "", def: "[to know (a person or place)]"},
    {word: "reservieren", fos: "", def: "[to reserve]"},
    {word: "putzen", fos: "", def: "[to clean]"},
    {word: "sitzen", fos: "", def: "[to sit]"},
    {word: "duzen", fos: "", def: "[to address someone with \"du\" (informal)]"},
    {word: "duschen", fos: "", def: "[to shower]"},
    {word: "finden", fos: "", def: "[to find, to think/feel]"},
    {word: "antworten", fos: "", def: "[to answer]"},
    {word: "öffnen", fos: "", def: "[to open]"},
    {word: "auch", fos: "", def: "[also, too]"},
    {word: "mir", fos: "", def: "[to me] (Dative of ich)"},
    {word: "nicht", fos: "", def: "[not]"},
    {word: "schlecht", fos: "", def: "[bad]"},
    {word: "dir", fos: "", def: "[to you] (Dative of du)"},
    {word: "Ihnen", fos: "", def: "[to you] (Formal Dative of Sie)"},
    {word: "nan", fos: "", def: "[zero]"},
    {word: "eins", fos: "", def: "[one]"},
    {word: "zwei", fos: "", def: "[two]"},
    {word: "drei", fos: "", def: "[three]"},
    {word: "vier", fos: "", def: "[four]"},
    {word: "fünf", fos: "", def: "[five]"},
    {word: "sieben", fos: "", def: "[seven]"},
    {word: "acht", fos: "", def: "[eight]"},
    {word: "neun", fos: "", def: "[nine]"},
    {word: "zehn", fos: "", def: "[ten]"},
    {word: "Wohnort", fos: "", def: "[place of residence]"},
    {word: "Handynummer", fos: "", def: "[cell phone number]"},
    {word: "Persönliche Daten", fos: "", def: "[personal data / details]"},
    {word: "Anrede", fos: "", def: "[salutation, form of address]"},
    {word: "Herr", fos: "", def: "[Mr. / gentleman]"},
    {word: "Frau", fos: "", def: "[Mrs. / Ms. / woman]"},
];
