export const words = [
    {word: "ballast", fos: "n.", def: "Heavy material used to make a ship steady or control the rising and falling of a vessel like a balloon."},
    {word: "buoyant", fos: "adj.", def: "Able to float."},
    {word: "buoyant", fos: "adj.", def: "Cheerful and carefree."},
    {word: "buoyancy", fos: "n.", def: "The ability to float."},
    {word: "clamber", fos: "v.", def: "To climb awkwardly."},
    {word: "detach", fos: "v.", def: "To separate from."},
    {word: "detached", fos: "adj.", def: "Not connected."},
    {word: "detached", fos: "adj.", def: "Lacking concern; not taking sides."},
    {word: "eerie", fos: "adj.", def: "Causing uneasiness; strange or mysterious."},
    {word: "fathom", fos: "n.", def: "A length of six feet, used in measuring the depth of water."},
    {word: "fathom", fos: "v.", def: "To figure out; to understand."},
    {word: "pique", fos: "v.", def: "To arouse or excite."},
    {word: "pique", fos: "n.", def: "A feeling of resentment caused by being ignored, insulted, etc."},
    {word: "probe", fos: "v.", def: "To poke or prod."},
    {word: "probe", fos: "v.", def: "To examine closely."},
    {word: "probe", fos: "n.", def: "A long, slender instrument used to examine a wound or part of the body."},
    {word: "probe", fos: "n.", def: "A thorough investigation."},
    {word: "realize", fos: "v.", def: "To be aware of."},
    {word: "realize", fos: "v.", def: "To bring into being; to make happen."},
    {word: "rupture", fos: "v.", def: "To split or break."},
    {word: "rupture", fos: "n.", def: "A breaking or tearing apart by force."},
    {word: "rupture", fos: "n.", def: "The breaking of a friendly relationship."},
    {word: "sphere", fos: "n.", def: "An object with all points on its surface equally distant from its center; a ball or globe."},
    {word: "sphere", fos: "n.", def: "An area of power, influence, or activity."},
    {word: "spherical", fos: "adj.", def: "Of or relating to the shape of a sphere."},
    {word: "submerge", fos: "v.", def: "To go underwater."},
    {word: "submerge", fos: "v.", def: "To put underwater or cover with water."},
    {word: "tedious", fos: "adj.", def: "Seeming to go on for a long time; boring."},
    {word: "tedium", fos: "n.", def: "Boredom."},
    {word: "ultimate", fos: "adj.", def: "Final."},
    {word: "ultimate", fos: "adj.", def: "The greatest possible; maximum."},
    {word: "ultimate", fos: "n.", def: "Something that is the greatest; the maximum."},
    {word: "unscathed", fos: "adj.", def: "Completely unharmed."},
    {word: "abduct", fos: "v.", def: "To carry away by force; to kidnap."},
    {word: "abduction", fos: "n.", def: "The act or instance of abducting."},
    {word: "abode", fos: "n.", def: "The place where one lives; home."},
    {word: "abyss", fos: "n.", def: "A deep opening in the earth."},
    {word: "abyss", fos: "n.", def: "Anything too deep to measure."},
    {word: "arbitrate", fos: "v.", def: "To settle a disagreement between two parties by having a third party make a decision after hearing both sides."},
    {word: "arbitration", fos: "n.", def: "The act of arbitrating."},
    {word: "attribute", fos: "v.", def: "To think of as coming from or belonging to a particular person or thing."},
    {word: "attribute", fos: "n.", def: "A quality or feature associated with a person or thing."},
    {word: "capricious", fos: "adj.", def: "Likely to change quickly for no obvious reason."},
    {word: "compromise", fos: "v.", def: "To settle a disagreement by having each side give up something."},
    {word: "compromise", fos: "v.", def: "To expose to the possiblity of criticism or shame."},
    {word: "compromise", fos: "n.", def: "A settlement reached by each side giving up something."},
    {word: "devout", fos: "adj.", def: "Very religious."},
    {word: "devout", fos: "adj.", def: "Sincere."},
    {word: "distraught", fos: "adj.", def: "Deeply disturbed; very troubled."},
    {word: "enlighten", fos: "v.", def: "To inform or instruct; to give knowledge or truth to."},
    {word: "enlightened", fos: "adj.", def: "Free from ignorance or prejudice."},
    {word: "incline", fos: "v.", def: "To slope or lean."},
    {word: "incline", fos: "v.", def: "To be likely to; to have a fondness for."},
    {word: "incline", fos: "v.", def: "To bend or bow (the head)."},
    {word: "incline", fos: "n.", def: "A sloping surface."},
    {word: "intervene", fos: "v.", def: "To enter in order to help or settle something."},
    {word: "intervention", fos: "n.", def: "The act or instance of intervening."},
    {word: "necessity", fos: "n.", def: "Anything that cannot be done without or that is greatly needed."},
    {word: "necessity", fos: "n.", def: "The condition of beeing needed."},
    {word: "orbit", fos: "n.", def: "The path taken by an object around a heavenly body such as a a star, planet, or moon."},
    {word: "orbit", fos: "v.", def: "To put into or be in orbit."},
    {word: "sacred", fos: "adj.", def: "Holy; having to do with religion."},
    {word: "sacred", fos: "adj.", def: "Worthy of being given the greatest honor or respect."},
    {word: "arduous", fos: "adj.", def: "Requiring much effort; very difficult."},
    {word: "canny", fos: "adj.", def: "Shrewd and careful; watchful of one's own interests."},
    {word: "climax", fos: "n.", def: "The highest point; the greatest moment or event."},
    {word: "endorse", fos: "v.", def: "To sign the back of a check before cashing or depositing it."},
    {word: "endorse", fos: "v.", def: "To approve of; to support."},
    {word: "endorse", fos: "v.", def: "To be favorably associated with a product in return for payment."},
    {word: "exuberant", fos: "adj.", def: "Happy and excited; bubbling over with enthusiasm."},
    {word: "exuberance", fos: "n.", def: "The quality of being exuberant."},
    {word: "intrepid", fos: "adj.", def: "Feeling or showing no fear; brave; courageous."},
    {word: "kindle", fos: "v.", def: "To start burning."},
    {word: "kindle", fos: "v.", def: "To cause to become excited or stirred up."},
    {word: "kindling", fos: "n.", def: "Sticks used to start a fire."},
    {word: "lucrative", fos: "adj.", def: "Producing wealth or profit."},
    {word: "mentor", fos: "n.", def: "A wise and loyal friend and adviser."},
    {word: "obsession", fos: "n.", def: "An interest, idea, or feeling that fills one's mind and leaves little room for anything else."},
    {word: "personable", fos: "adj.", def: "Pleasing in manner and appearance."},
    {word: "proficient", fos: "adj.", def: "Able to do something very well; skillful."},
    {word: "proficiency", fos: "n.", def: "The quality of being proficient."},
    {word: "scanty", fos: "adj.", def: "Not enough or just barely enough; small in size or amount."},
    {word: "strait", fos: "n.", def: "A narrow body of water connecting two larger ones."},
    {word: "straits", fos: "n.", def: "Trouble or need."},
    {word: "zest", fos: "n.", def: "Great enjoyment; excitement."},
    {word: "zestful", fos: "adj.", def: "Full of zest."}
];
