export const words = [
  {word: "spectator", fos: "n.", def: "a person who watches an activity, especially a sports event, without taking part."},
  {word: "intricate", fos: "adj.", def: "having a lot of small parts that are arranged in a complicated or delicate way."},
  {word: "appointment", fos: "n.", def: "an arrangement to meet someone at a particular time and place."},
  {word: "keen", fos: "adj.", def: "(of an awareness or ability) very developed, or (of the mind) very quick to understand."},
  {word: "fortune", fos: "n.", def: "a large amount of money, goods, property, etc."},
  {word: "egotism", fos: "n.", def: "thinking only about yourself and considering yourself better and more important than other people."},
  {word: "enlarge", fos: "v.", def: "to become bigger or to make somehting bigger."},
  {word: "submerge", fos: "v.", def: "to cover over; suppress; hide."},
  {word: "simultaneously", fos: "adv.", def: "at the same time."},
  {word: "sterile", fos: "adj.", def: "(of land) unable to produce plants or crops."},
  {word: "abstarct", fos: "adj.", def: "relating to ideas and not real things."},
  {word: "nostalgia", fos: "n.", def: "a feeling of happiness mixed with sadness when you think about things that happened in the past."},
  {word: "chaotic", fos: "adj.", def: "in a state of complete disorder and confusion."},
  {word: "adolescence", fos: "n.", def: "the period of time in a person's life when they are developing into an adult."},
  {word: "shame", fos: "n.", def: "uncomfortable feeling that you get when  you have done something wrong or embarrassing."},
  {word: "vividly", fos: "adv.", def: "in a way that is very clear, powerful, and detailed in your mind."},
  {word: "futile", fos: "adj.", def: "certain not to have a successful effect or result."},
  {word: "impoverished", fos: "adj.", def: "very poor."},
  {word: "prosperity", fos: "n.", def: "a situation in which someone is successful, usually by earning a lot of money."},
  {word: "grit", fos: "n.", def: "courage and determination despite difficulty."},
  {word: "poverty", fos: "n.", def: "a state or condition in which a person or community lacks the financial resources and essentials for a minimum standrad of living."},
  {word: "vague", fos: "adj.", def: "not clearly expressed, known, described, or decided."},
  {word: "poignantly", fos: "adv.", def: "in a way that causes or has a very sharp feeling of sadness."},
  {word: "imminence", fos: "n.", def: "the state of being likely to happen very soon, or coming very soon."},
  {word: "inferior", fos: "adj.", def: "not as good as someone or something else."},
  {word: "innocence", fos: "n.", def: "the quality of not having much experience of life and not knowing about the bad things that happen in life."},
  {word: "reverie", fos: "n.", def: "daydreaming."},
  {word: "reinforce", fos: "v.", def: "to give added strength or support to."},
  {word: "enchantment", fos: "n.", def: "a change caused by magic, or the state of being changed by magic."},
  {word: "decay", fos: "n.", def: "to become gradually damaged, worse or less; to cause something to do this."},
  {word: "monotonous", fos: "adj.", def: "always the same and boring."},
  {word: "retribution", fos: "n.", def: "deserved and severe punishment."},
  {word: "necessity", fos: "n.", def: "something that you need, especially in order to live."},
  {word: "exploit", fos: "n.", def: "something unusual, brave, or funny that someone has done."},
  {word: "vigor", fos: "n.", def: "strength, energy, or enthusiasm."},
  {word: "intimidate", fos: "v.", def: "to frighten or threaten someone."},
  {word: "preoccupied", fos: "adj.", def: "thinking or worrying about something to much."},
  {word: "impotent", fos: "n.", def: "not having the power or ability to change or improve a situation."},
  {word: "malicious", fos: "adj.", def: "having or showing a desire to cause harm to someone."},
  {word: "destruction", fos: "n.", def: "the act of destroying something, or the fact of being destroyed."},
  {word: "rage", fos: "n.", def: "(a period of) extreme or violent anger."},
  {word: "immobile", fos: "n.", def: "not moving or not able to move."},
  {word: "compassion", fos: "n.", def: "a strong feeling of sympathy and sadness for the suffereing or bad luck of others and a wish to help them."},
  {word: "awkward", fos: "n.", def: "not having grace or skill; clumsy."},
  {word: "barren", fos: "adj.", def: "(of land) too poor to produce much or any vegetation."}
];