export const words = [
  {word: "spectator", fos: "n.", def: "a person who watches an activity, especially a sports event, without taking part."},
  {word: "intricate", fos: "adj.", def: "having a lot of small parts that are arranged in a complicated or delicate way."},
  {word: "appointment", fos: "n.", def: "an arrangement to meet someone at a particular time and place."},
  {word: "keen", fos: "adj.", def: "(of an awareness or ability) very developed, or (of the mind) very quick to understand."},
  {word: "fortune", fos: "n.", def: "a large amount of money, goods, property, etc."},
  {word: "egotism", fos: "n.", def: "thinking only about yourself and considering yourself better and more important than other people."},
  {word: "enlarge", fos: "v.", def: "to become bigger or to make something bigger."},
  {word: "submerge", fos: "v.", def: "to cover over; suppress; hide."},
  {word: "simultaneously", fos: "adv.", def: "at the same time."},
  {word: "sterile", fos: "adj.", def: "(of land) unable to produce plants or crops."},
  {word: "abstract", fos: "adj.", def: "relating to ideas and not real things."},
  {word: "nostalgia", fos: "n.", def: "a feeling of happiness mixed with sadness when you think about things that happened in the past."},
  {word: "chaotic", fos: "adj.", def: "in a state of complete disorder and confusion."},
  {word: "adolescence", fos: "n.", def: "the period of time in a person's life when they are developing into an adult."},
  {word: "shame", fos: "n.", def: "uncomfortable feeling that you get when  you have done something wrong or embarrassing."},
  {word: "vividly", fos: "adv.", def: "in a way that is very clear, powerful, and detailed in your mind."},
  {word: "futile", fos: "adj.", def: "certain not to have a successful effect or result."},
  {word: "impoverished", fos: "adj.", def: "very poor."},
  {word: "prosperity", fos: "n.", def: "a situation in which someone is successful, usually by earning a lot of money."},
  {word: "grit", fos: "n.", def: "courage and determination despite difficulty."},
  {word: "poverty", fos: "n.", def: "a state or condition in which a person or community lacks the financial resources and essentials for a minimum standard of living."},
  {word: "vague", fos: "adj.", def: "not clearly expressed, known, described, or decided."},
  {word: "poignantly", fos: "adv.", def: "in a way that causes or has a very sharp feeling of sadness."},
  {word: "imminence", fos: "n.", def: "the state of being likely to happen very soon, or coming very soon."},
  {word: "inferior", fos: "adj.", def: "not as good as someone or something else."},
  {word: "innocence", fos: "n.", def: "the quality of not having much experience of life and not knowing about the bad things that happen in life."},
  {word: "reverie", fos: "n.", def: "daydreaming."},
  {word: "reinforce", fos: "v.", def: "to give added strength or support to."},
  {word: "enchantment", fos: "n.", def: "a change caused by magic, or the state of being changed by magic."},
  {word: "decay", fos: "n.", def: "to become gradually damaged, worse or less; to cause something to do this."},
  {word: "monotonous", fos: "adj.", def: "always the same and boring."},
  {word: "retribution", fos: "n.", def: "deserved and severe punishment."},
  {word: "necessity", fos: "n.", def: "something that you need, especially in order to live."},
  {word: "exploit", fos: "n.", def: "something unusual, brave, or funny that someone has done."},
  {word: "vigor", fos: "n.", def: "strength, energy, or enthusiasm."},
  {word: "intimidate", fos: "v.", def: "to frighten or threaten someone."},
  {word: "preoccupied", fos: "adj.", def: "thinking or worrying about something to much."},
  {word: "impotent", fos: "n.", def: "not having the power or ability to change or improve a situation."},
  {word: "malicious", fos: "adj.", def: "having or showing a desire to cause harm to someone."},
  {word: "destruction", fos: "n.", def: "the act of destroying something, or the fact of being destroyed."},
  {word: "rage", fos: "n.", def: "(a period of) extreme or violent anger."},
  {word: "immobile", fos: "n.", def: "not moving or not able to move."},
  {word: "compassion", fos: "n.", def: "a strong feeling of sympathy and sadness for the suffering or bad luck of others and a wish to help them."},
  {word: "awkward", fos: "n.", def: "not having grace or skill; clumsy."},
  {word: "barren", fos: "adj.", def: "(of land) too poor to produce much or any vegetation."},
  {word: "boisterous", fos: "adj.", def: "noisy, energetic, and rough."},
  {word: "reprimand", fos: "n.", def: "strong official criticism of a person or their behavior."},
  {word: "conduct", fos: "v.", def: "organize and carry out."},
  {word: "devote", fos: "v.", def: "give all or a large part of one's time or resources to (a person, activity, or cause.)"},
  {word: "precede", fos: "v.", def: "come before (something) in time."},
  {word: "thoroughly", fos: "adv.", def: "completely; in a way that includes many details."},
  {word: "discard", fos: "v.", def: "get rid of (someone or something.)"},
  {word: "perfunctory", fos: "adj.", def: "done quickly, without taking care or interest; mechanical."},
  {word: "ritual", fos: "n.", def: "a formal ceremony or series of acts that is always performed in the same way."},
  {word: "draw", fos: "v.", def: "select (a ticket or name) randomly to decide winners in a lottery."},
  {word: "gravely", fos: "adv.", def: "seriously."},
  {word: "defiantly", fos: "adv.", def: "in a way that proudly refuses to obey authority."},
  {word: "quaver", fos: "v.", def: "to shake or tremble in speaking."},
  {word: "momentary", fos: "adj.", def: "lasting for a very short time."},
  {word: "penalty", fos: "n.", def: "a punishment imposed for breaking a law, rule, or contract."},
  {word: "vanish", fos: "v.", def: "disappear suddenly and completely."},
  {word: "dictatorship", fos: "n.", def: "a form of government where absolute power is concentrated in one leader."},
  {word: "annihilate", fos: "v.", def: "to destroy completely."},
  {word: "chaos", fos: "n.", def: "complete disorder and confusion."},
  {word: "sterilize", fos: "v.", def: "to make free from bacteria or other living microorganisms."},
  {word: "paradox", fos: "n.", def: "a statement that contradicts itself but might still be true."},
  {word: "resilient", fos: "adj.", def: "able to withstand or recover quickly from difficult conditions."},
  {word: "undulate", fos: "v.", def: "to move in a wave-like motion."},
  {word: "helplessness", fos: "n.", def: "a state of being unable to help oneself; lacking strength or power."},
  {word: "engulf", fos: "v.", def: "to surround and cover something or someone completely."},
  {word: "malfunction", fos: "v.", def: "a failure to work or operate correctly."},
  {word: "primeval", fos: "adj.", def: "of or relating to the earliest ages."},
  {word: "forfeit", fos: "v.", def: "to lose or give up something as a penalty for wrongdoing."},
  {word: "revoke", fos: "v.", def: "to officially cancel the power or effect of something."},
  {word: "subtle", fos: "adj.", def: "so delicate or precise as to be difficult to analyze or describe."},
  {word: "vigilance", fos: "n.", def: "more careful attention, especially in order to notice possible danger."},
  {word: "clammy", fos: "adj.", def: "sticky and slightly wet in an unpleasant way."},
  {word: "handicap", fos: "n.", def: "something that makes it difficult for you to do something."},
  {word: "toy with", fos: "phr. v.", def: "to consider something or doing something, but not in a very serious way, and without making a decision."},
  {word: "wince", fos: "adj.", def: "to show pain or embarrassment suddenly and for a short time in the face."},
  {word: "envious", fos: "adj.", def: "wishing you had what another person has."},
  {word: "resemblance", fos: "n.", def: "the fact that two people or things look like each other or are similar in some other way."},
  {word: "abnormal", fos: "adj.", def: "different from what is usual or average, especially in a way that is bad."},
  {word: "bargain", fos: "n.", def: "something on sale at a lower price than its true value."},
  {word: "luminous", fos: "adj.", def: "very beautiful, bright or shining, especially in the dark."},
  {word: "overthrow", fos: "v.", def: "to defeat or remove someone from power, using force."},
  {word: "calibrate", fos: "v.", def: "to mark units of measurement on an instrument such so that it can measure accurately."},
  {word: "spectacles", fos: "n.", def: "glasses."},
  {word: "symmetry", fos: "n.", def: "the quality of having parts that match each other, especially in a way that is attractive, or similarity of shape or contents."},
  {word: "offset", fos: "v.", def: "to balance one influence against an opposing influence, so that there is no great difference as a result."},
  {word: "collision", fos: "n.", def: "an accident that happens when two vehicles hit each other with force."},
  {word: "synchronize", fos: "v.", def: "to (cause to) happen at the same time."}
];