export const words = [
    {word: "abate", fos: "v.", def: "To become weaker; to decrease."},
    {word: "acknowledge", fos: "v.", def: "To admit the existence of."},
    {word: "agent", fos: "n.", def: "A person who acts or does business for another."},
    {word: "authority", fos: "n.", def: "The right to give orders, make decisions, or take action."},
    {word: "devastate", fos: "v.", def: "To ruin or destroy completely."},
    {word: "epidemic", fos: "n.", def: "The rapid spreading of a disease to many people at one time."},
    {word: "estimate", fos: "n.", def: "A number that is not exact; a careful guess."},
    {word: "evict", fos: "v.", def: "To force out of property by taking legal action."},
    {word: "impartial", fos: "adj.", def: "Not favoring one side more than another; fair."},
    {word: "industrious", fos: "adj.", def: "Hardworking; not lazy."},
    {word: "infuriate", fos: "v.", def: "To make very angry."},
    {word: "irrelevant", fos: "adj.", def: "Having nothing to do with the subject."},
    {word: "precise", fos: "adj.", def: "Exact; specific."},
    {word: "sham", fos: "n.", def: "Something fake or false."},
    {word: "trek", fos: "n.", def: "A long, slow, and difficult journey."},
    {word: "astute", fos: "adj.", def: "Wise in a clever or practical way."},
    {word: "authentic", fos: "adj.", def: "Genuine; true."},
    {word: "delicacy", fos: "n.", def: "A choice item of food."},
    {word: "derogatory", fos: "adj.", def: "Expressing a low opinion; intended to hurt the reputation of a person or thing."},
    {word: "devour", fos: "v.", def: "To eat up hungrily."},
    {word: "figment", fos: "n.", def: "Something that is made up in the mind but that has no connection with reality."},
    {word: "mythical", fos: "adj.", def: "Imaginary; not real."},
    {word: "plumage", fos: "n.", def: "A bird's feathers."},
    {word: "predatory", fos: "adj.", def: "Living by killing and eating other animals."},
    {word: "prior", fos: "adj.", def: "Coming earlier in time."},
    {word: "scavenge", fos: "v.", def: "To search through and pick over, looking for something usable."},
    {word: "slaughter", fos: "v.", def: "To kill in order to obtain meat."},
    {word: "solitude", fos: "n.", def: "The condition of being alone or at some distance from people."},
    {word: "ungainly", fos: "adj.", def: "Moving in a clumsy or awkward way."},
    {word: "vulnerable", fos: "adj.", def: "Open to attack; easily injured physically and emotionally."},
    {word: "admonish", fos: "v.", def: "To warn."},
    {word: "aghast", fos: "adj.", def: "Struck with horror; shocked."},
    {word: "annihilate", fos: "v.", def: "To destroy completely; to reduce to utter ruin."},
    {word: "benefactor", fos: "n.", def: "A person who provides help, especially by giving money."},
    {word: "bestow", fos: "v.", def: "To give as an honor; to present as a gift."},
    {word: "devious", fos: "adj.", def: "Having many twists and turns; winding."},
    {word: "devoid", fos: "adj.", def: "Lacking; empty; entirely without."},
    {word: "heed", fos: "v.", def: "To pay attention to."},
    {word: "mortal", fos: "n.", def: "A human being, especially as contrasted with a god."},
    {word: "muse", fos: "v.", def: "To think about in a quiet, careful way."},
    {word: "pioneer", fos: "n.", def: "A person who goes before others and opens the way for them to follow."},
    {word: "plague", fos: "n.", def: "A deadly disease that spreads rapidly from person to person."},
    {word: "subside", fos: "v.", def: "To sink to a lower level."},
    {word: "unwitting", fos: "adj.", def: "Not done on purpose; unintended."},
    {word: "wrath", fos: "n.", def: "Forceful anger; fury."},
];
