export const words = [
    {word: "abate", fos: "v.", def: "To become weaker; to decrease."},
    {word: "acknowledge", fos: "v.", def: "To admit the existence of."},
    {word: "agent", fos: "n.", def: "A person who acts or does business for another."},
    {word: "authority", fos: "n.", def: "The right to give orders, make decisions, or take action."},
    {word: "devastate", fos: "v.", def: "To ruin or destroy completely."},
    {word: "epidemic", fos: "n.", def: "The rapid spreading of a disease to many people at one time."},
    {word: "estimate", fos: "n.", def: "A number that is not exact; a careful guess."},
    {word: "evict", fos: "v.", def: "To force out of property by taking legal action."},
    {word: "impartial", fos: "adj.", def: "Not favoring one side more than another; fair."},
    {word: "industrious", fos: "adj.", def: "Hardworking; not lazy."},
    {word: "infuriate", fos: "v.", def: "To make very angry."},
    {word: "irrelevant", fos: "adj.", def: "Having nothing to do with the subject."},
    {word: "precise", fos: "adj.", def: "Exact; specific."},
    {word: "sham", fos: "n.", def: "Something fake or false."},
    {word: "trek", fos: "n.", def: "A long, slow, and difficult journey."},
    {word: "astute", fos: "adj.", def: "Wise in a clever or practical way."},
    {word: "authentic", fos: "adj.", def: "Genuine; true."},
    {word: "delicacy", fos: "n.", def: "A choice item of food."},
    {word: "derogatory", fos: "adj.", def: "Expressing a low opinion; intended to hurt the reputation of a person or thing."},
    {word: "devour", fos: "v.", def: "To eat up hungrily."},
    {word: "figment", fos: "n.", def: "Something that is made up in the mind but that has no connection with reality."},
    {word: "mythical", fos: "adj.", def: "Imaginary; not real."},
    {word: "plumage", fos: "n.", def: "A bird's feathers."},
    {word: "predatory", fos: "adj.", def: "Living by killing and eating other animals."},
    {word: "prior", fos: "adj.", def: "Coming earlier in time."},
    {word: "scavenge", fos: "v.", def: "To search through and pick over, looking for something usable."},
    {word: "slaughter", fos: "v.", def: "To kill in order to obtain meat."},
    {word: "solitude", fos: "n.", def: "The condition of being alone or at some distance from people."},
    {word: "ungainly", fos: "adj.", def: "Moving in a clumsy or awkward way."},
    {word: "vulnerable", fos: "adj.", def: "Open to attack; easily injured physically and emotionally."},
    {word: "admonish", fos: "v.", def: "To warn."},
    {word: "aghast", fos: "adj.", def: "Struck with horror; shocked."},
    {word: "annihilate", fos: "v.", def: "To destroy completely; to reduce to utter ruin."},
    {word: "benefactor", fos: "n.", def: "A person who provides help, especially by giving money."},
    {word: "bestow", fos: "v.", def: "To give as an honor; to present as a gift."},
    {word: "devious", fos: "adj.", def: "Having many twists and turns; winding."},
    {word: "devoid", fos: "adj.", def: "Lacking; empty; entirely without."},
    {word: "heed", fos: "v.", def: "To pay attention to."},
    {word: "mortal", fos: "n.", def: "A human being, especially as contrasted with a god."},
    {word: "muse", fos: "v.", def: "To think about in a quiet, careful way."},
    {word: "pioneer", fos: "n.", def: "A person who goes before others and opens the way for them to follow."},
    {word: "plague", fos: "n.", def: "A deadly disease that spreads rapidly from person to person."},
    {word: "subside", fos: "v.", def: "To sink to a lower level."},
    {word: "unwitting", fos: "adj.", def: "Not done on purpose; unintended."},
    {word: "wrath", fos: "n.", def: "Forceful anger; fury."},
    {word: "acquire", fos: "v.", def: "To gain ownership of something; to get by one's own efforts or actions."},
    {word: "antagonize", fos: "v.", def: "To make an enemy of; to stir up anger or dislike."},
    {word: "competent", fos: "adj.", def: "Having the ability to do what is needed."},
    {word: "comprise", fos: "v.", def: "To form; to make up."},
    {word: "correspond", fos: "v.", def: "To match; to be equal to."},
    {word: "dilapidated", fos: "adj.", def: "In poor condition from neglect or age."},
    {word: "illustrious", fos: "adj.", def: "Very famous; outstanding."},
    {word: "incident", fos: "n.", def: "Something that happens in real life or in a story; an event, often of little importance."},
    {word: "inherit", fos: "v.", def: "To receive something from someone after that person's death."},
    {word: "latitude", fos: "n.", def: "The distance north or south of the equator, measured in degrees."},
    {word: "loath", fos: "adj.", def: "Unwilling; reluctant."},
    {word: "maintain", fos: "v.", def: "To declare something to be true."},
    {word: "renovate", fos: "v.", def: "To make like new again."},
    {word: "reprimand", fos: "v.", def: "To scold in a harsh or formal manner."},
    {word: "supervise", fos: "v.", def: "To direct or manage activities."},
    {word: "adequate", fos: "adj.", def: "Enough; sufficient."},
    {word: "administer", fos: "v.", def: "To manage or direct."},
    {word: "agitate", fos: "v.", def: "To disturb or upset."},
    {word: "capitulate", fos: "v.", def: "To give in; to surrender."},
    {word: "citrus", fos: "n.", def: "A fruit of the family that includes oranges, lemons, grapefruits, and limes."},
    {word: "disrupt", fos: "v.", def: "To break up the orderly course of."},
    {word: "hovel", fos: "n.", def: "An unpleasant, cramped, and dilapidated place to live."},
    {word: "illiterate", fos: "adj.", def: "Unable to read or write."},
    {word: "indifferent", fos: "adj.", def: "Not concerned about; not caring."},
    {word: "menial", fos: "adj.", def: "Of or relating to low-level, humble work."},
    {word: "permanent", fos: "adj.", def: "Lasting or expected to last for a long time."},
    {word: "respite", fos: "n.", def: "A period of rest; a pause."},
    {word: "strenuous", fos: "adj.", def: "Needing much effort; using a lot of energy."},
    {word: "toil", fos: "v.", def: "To work long and hard."},
    {word: "urgent", fos: "adj.", def: "Needing quick action or attention."},
    {word: "addict", fos: "n.", def: "A person with a very strong desire for something that is habit-forming and sometimes harmful."},
    {word: "aspire", fos: "v.", def: "To have a strong desire to get or do something; to seek."},
    {word: "bias", fos: "n.", def: "A preference that prevents one from being impartial; prejudice."},
    {word: "blatant", fos: "adj.", def: "Very obvious in an offensive or shameless way."},
    {word: "candid", fos: "adj.", def: "Expressed honestly and without holding back unpleasant truths."},
    {word: "confront", fos: "v.", def: "To stand up to; to face boldly."},
    {word: "debut", fos: "n.", def: "A first public appearance."},
    {word: "enroll", fos: "v.", def: "To sign up to become a member of some group or activity; to register."},
    {word: "fluster", fos: "v.", def: "To make nervous, embarrassed, or confused."},
    {word: "impunity", fos: "n.", def: "Freedom from being harmed or punished."},
    {word: "intensify", fos: "v.", def: "To increase, to strengthen or deepen."},
    {word: "intimidate", fos: "v.", def: "To frighten, especially by threatening someone."},
    {word: "obnoxious", fos: "adj.", def: "Very unpleasant; disgusting."},
    {word: "retort", fos: "v.", def: "To answer, especially in a quick or clever way."},
    {word: "stint", fos: "n.", def: "A period of time devoted to a job or some task."},
    {word: "beseech", fos: "v.", def: "To ask earnestly; to beg."},
    {word: "consternation", fos: "n.", def: "Amazement or fear that makes one feel confused."},
    {word: "delectable", fos: "adj.", def: "Pleasing to the senses, especially to the sense of taste; delicious."},
    {word: "garland", fos: "n.", def: "A wreath or chain of leaves and flowers."},
    {word: "gratify", fos: "v.", def: "To please or satisfy."},
    {word: "haughty", fos: "adj.", def: "Showing too much pride in oneself and scorn or contempt for others."},
    {word: "impetuous", fos: "adj.", def: "Likely to act without thinking; hasty."},
    {word: "lavish", fos: "adj.", def: "Much more than enough."},
    {word: "pluck", fos: "v.", def: "To pull off or out; to pick."},
    {word: "ponder", fos: "v.", def: "To think about; to consider carefully."},
    {word: "privilege", fos: "n.", def: "A special favor, right, or advantage given to a person or group."},
    {word: "porstrate", fos: "adj.", def: "Lying flat."},
    {word: "rapture", fos: "n.", def: "A state of great joy, delight, or love."},
    {word: "revelry", fos: "n.", def: "Noisy merrymaking."},
    {word: "whim", fos: "n.", def: "A sudden wish to do something without a particular reason; a fanciful idea."},
    {word: "acrid", fos: "adj.", def: "Sharp, irritating, or bitter to the sense of taste or smell."},
    {word: "casualty", fos: "n.", def: "A person killed or injured in a war or accident."},
    {word: "congested", fos: "adj.", def: "Overcrowded; filled too full."},
    {word: "cope", fos: "v.", def: "To manage problems or difficulties successfully."},
    {word: "headlong", fos: "adj.", def: "With great speed or force; reckless."},
    {word: "hurtle", fos: "v.", def: "To move with great force and speed."},
    {word: "impede", fos: "v.", def: "To get in the way of; to interfere with the movement of."},
    {word: "inevitable", fos: "adj.", def: "Bound to happen; unavoidable."},
    {word: "initiate", fos: "v.", def: "To put into effect; to bring into use."},
    {word: "irate", fos: "adj.", def: "Very angry; furious."},
    {word: "lax", fos: "adj.", def: "Not strictly enforced; undemanding; careless."},
    {word: "negligent", fos: "adj.", def: "Failing to take proper care of or to give proper attention to."},
    {word: "smolder", fos: "v.", def: "To burn slowly without bursting into flames."},
    {word: "stringent", fos: "adj.", def: "Strict; severe."},
    {word: "throng", fos: "n.", def: "A large number of people gathered together; a crowd."},
    {word: "dumbfound", fos: "v.", def: "To make speechless with amazement."},
    {word: "ensue", fos: "v.", def: "To follow; to come as a result of or at a later time."},
    {word: "era", fos: "n.", def: "A particular period in history."},
    {word: "flourish", fos: "v.", def: "To thrive or prosper."},
    {word: "garrison", fos: "n.", def: "Soldiers stationed in a place to protect it."},
    {word: "grievous", fos: "adj.", def: "Causing grief or pain; hard to bear."},
    {word: "hoard", fos: "v.", def: "To save and put away, especially secretly."},
    {word: "inundate", fos: "v.", def: "To cover, as with water from a flood."},
    {word: "invincible", fos: "adj.", def: "Impossible to defeat."},
    {word: "nomad", fos: "n.", def: "A member of a group that settles briefly in one place and then moves on to another."},
    {word: "placate", fos: "v.", def: "To stop from being angry; to calm."},
    {word: "principal", fos: "adj.", def: "Most important."},
    {word: "recede", fos: "v.", def: "To move back or to drop to a lower level."},
    {word: "ruthless", fos: "adj.", def: "Showing no mercy; pitiless."},
    {word: "sacrifice", fos: "n.", def: "Something given up for the sake of another."},
    {word: "aquatic", fos: "adj.", def: "Growing or living in or on water."},
    {word: "assert", fos: "v.", def: "To say firmly; to declare."},
    {word: "avert", fos: "v.", def: "To turn away."},
    {word: "bleak", fos: "adj.", def: "Without much hope."},
    {word: "blithe", fos: "adj.", def: "Cheerful; carefree."},
    {word: "docile", fos: "adj.", def: "Well behaved; easy to handle."},
    {word: "dwindle", fos: "v.", def: "To continue becoming less; to grow smaller in number or amount."},
    {word: "lethal", fos: "adj.", def: "Causing, or capable of, death."},
    {word: "monitor", fos: "v.", def: "To watch closely and frequently; to observe and make note."},
    {word: "mutilate", fos: "v.", def: "To hurt or damage by cutting into, cutting off, or cutting out."},
    {word: "nimble", fos: "adj.", def: "Able to move quickly and easily."},
    {word: "plight", fos: "n.", def: "A difficult or dangerous condition or situation."},
    {word: "ponderous", fos: "adj.", def: "Heavy and slow moving."},
    {word: "verge", fos: "n.", def: "An edge, border, or brink."},
    {word: "vigilant", fos: "adj.", def: "Watchful; ready for danger."}
];
