export const words = [
  // The Story of an Hour
  {word: "afflicted", fos: "adj.", def: "suffering from pain, trouble, or unhappiness."},
  {word: "veiled", fos: "adj.", def: "hidden or not expressed directly."},
  {word: "intelligence", fos: "n.", def: "the ability to learn, understand, and think; information, news; secret information that a government collects about an enemy or possible enemy."},
  {word: "hasten", fos: "v.", def: "to move or act quickly."},
  {word: "forestall", fos: "v.", def: "to stop (something) from happening or to cause (something) to happen at a later time; to act before (someone else) in order to prevent something."},
  {word: "bear", fos: "v.", def: "to accept or endure something difficult or unpleasant; to have or show a mark, sign, or feature; to carry or move something; to give birth to a child; to carry or deliver (a message, news, etc.)."},
  {word: "paralyzed", fos: "adj.", def: "unable to move or act."},
  {word: "exhaustion", fos: "n.", def: "the state of being very, very tired."},
  {word: "ware", fos: "n.", def: "things that are sold (such as goods, pottery, or tools)."},
  {word: "bespoke", fos: "v.", def: "showed, indicated."},
  {word: "bespoke", fos: "adj.", def: "custom-made."},
  {word: "repression", fos: "n.", def: "the act of stopping yourself from showing emotions or desires."},
  {word: "suspension", fos: "n.", def: "the act of stopping something for a short time."},
  {word: "elusive", fos: "adj.", def: "hard to find, catch, or understand."},
  {word: "tumultuously", fos: "adv.", def: "in a wild, noisy, and excited way."},
  {word: "strive", fos: "v.", def: "to try very hard to do or achieve something."},
  {word: "vacant", fos: "adj.", def: "empty; not filled or used."},
  {word: "keen", fos: "adj.", def: "having or showing strong interest or desire."},
  {word: "exalted", fos: "adj.", def: "very high in rank or status; or showing great joy."},
  {word: "dismiss", fos: "v.", def: "to decide not to think about something; to send someone away."},
  {word: "trivial", fos: "adj.", def: "not important, small in meaning."},
  {word: "persistence", fos: "n.", def: "continuing to do something even when it is hard."},
  {word: "implore", fos: "v.", def: "to ask for something very seriously; beg."},
  {word: "importunity", fos: "n.", def: "the act of asking for something again and again, in an annoying way."},
  {word: "feverish", fos: "adj.", def: "full of nervous excitement; like having a fever."},
  {word: "unwittingly", fos: "adv.", def: "without knowing or realizing."},
  {word: "descend", fos: "v.", def: "to move or go down from a higher place."},
  {word: "composedly", fos: "adv.", def: "calmly; in a controlled way."},
  
  // Thank You, Ma'am
  {word: "snatch", fos: "v.", def: "to quickly take something in a rough way."},
  {word: "snatch", fos: "n.", def: "the act of quickly taking something."},
  {word: "stoop", fos: "v.", def: "to bend your body forward and down."},
  {word: "stoop", fos: "n.", def: "a small raised area at the entrance of a house."},
  {word: "ashamed", fos: "adj.", def: "feeling shame or guilt."},
  {word: "frail", fos: "adj.", def: "weak or easily damaged (often about old or sick people)."},
  {word: "fix", fos: "v.", def: "to repair; to prepare food; to decide something."},
  {word: "presentable", fos: "adj.", def: "looking neat, clean, and good enough to be seen in public."},
  {word: "mistrusted", fos: "adj.", def: "not trusted; thought to be dishonest."},
  {word: "latch onto", fos: "phr. v.", def: "to grab and hold tightly; to become attached to."},
  {word: "behave oneself", fos: "phr.", def: "to act properly; to be polite and not cause trouble."},
  {word: "barren", fos: "adj.", def: "not able to produce plants; empty and lifeless."},
  
  // All Summer in a Day
  {word: "peer", fos: "v.", def: "to look closely or carefully at something."},
  {word: "peer", fos: "n.", def: "a person of the same age, rank, or group."},
  {word: "compound", fos: "v.", def: "to mix or combine."},
  {word: "compound", fos: "n.", def: "something made by combining parts."},
  {word: "tremble", fos: "v.", def: "to shake slightly because of fear, cold, or weakness."},
  {word: "protest", fos: "v.", def: "to show strong disagreement."},
  {word: "protest", fos: "n.", def: "a complaint or objection."},
  {word: "slacken", fos: "v.", def: "to become slower, weaker, or less active."},
  {word: "shove", fos: "v.", def: "to push roughly."},
  {word: "shove", fos: "n.", def: "a strong push."},
  {word: "drenched", fos: "adj.", def: "completely wet."},
  {word: "savagely", fos: "adv.", def: "in a violent or cruel way."},
  {word: "seize", fos: "v.", def: "to take hold of something quickly and strongly."},
  {word: "surge", fos: "v.", def: "to move suddenly forward in a crowd or wave."},
  {word: "surge", fos: "n.", def: "a sudden strong movement."},
  {word: "plead", fos: "v.", def: "to ask for something in an emotional way."},
  {word: "glance", fos: "v.", def: "to look quickly."},
  {word: "glance", fos: "n.", def: "a quick look."},
  {word: "tremor", fos: "n.", def: "a small shaking movement in the ground or body."},
  {word: "standstill", fos: "n.", def: "a state in which all activity stops."},
  {word: "immense", fos: "adj.", def: "very large or great."},
  {word: "squint", fos: "v.", def: "to partly close your eyes in order to see more clearly."},
  {word: "wail", fos: "v.", def: "to cry loudly in pain or sadness."},
  {word: "wail", fos: "n.", def: "a loud cry."},
  {word: "solemn", fos: "adj.", def: "very serious and formal."}
];
