export const words = [
    {word: "affection", fos: "n.", def: "a positive feeling of liking."},
    {word: "appeal", fos: "n.", def: "earnest or urgent request."},
    {word: "clasp", fos: "v.", def: "hold firmly and tightly."},
    {word: "conspicuous", fos: "adj.", def: "obvious to the eye or mind."},
    {word: "contribute", fos: "v.", def: "give, provide, or supply something."},
    {word: "declare", fos: "v.", def: "state emphatically and authoritatively."},
    {word: "eloquent", fos: "adj.", def: "expressing yourself readily, clearly, effectively."},
    {word: "exhibit", fos: "v.", def: "make visible or apparent."},
    {word: "ferry", fos: "n.", def: "a boat transporting people or vehicles over a body of water."},
    {word: "immigrant", fos: "n.", def: "a person who comes to a country in order to settle there."},
    {word: "lofty", fos: "adj.", def: "of imposing height; especially standing out above others."},
    {word: "pedestal", fos: "n.", def: "an architectural support or base."},
    {word: "persecute", fos: "v.", def: "cause to suffer."},
    {word: "poverty", fos: "n.", def: "the state of having little or no money and possessions."},
    {word: "unveil", fos: "v.", def: "make visible."},
    {word: "arrogant", fos: "adj.", def: "having or showing feelings of unwarranted importance."},
    {word: "boycott", fos: "n.", def: "refusal to have commercial dealings with some organization."},
    {word: "campaign", fos: "n.", def: "related operations aimed at achieving a particular goal."},
    {word: "ceremony", fos: "n.", def: "a formal event performed on a special occasion."},
    {word: "custody", fos: "n.", def: "guardianship over."},
    {word: "degrade", fos: "v.", def: "reduce in worth or character, usually verbally."},
    {word: "detain", fos: "v.", def: "cause to be slowed down or delayed."},
    {word: "extend", fos: "v.", def: "stretch out over a distance, space, time, or scope."},
    {word: "integrate", fos: "v.", def: "make into a whole or make part of a whole."},
    {word: "segregate", fos: "v.", def: "divide from the main body or mass and collect."},
    {word: "supreme", fos: "adj.", def: "greatest in status or authority or power."},
    {word: "triumph", fos: "n.", def: "a successful ending of a struggle or contest."},
    {word: "vacate", fos: "v.", def: "leave behind empty; move out of."},
    {word: "verdict", fos: "n.", def: "findings of a jury on issues submitted to it for decision."},
    {word: "violate", fos: "v.", def: "fail to agree with; go against."},
    {word: "abundant", fos: "adj.", def: "present in great quantity."},
    {word: "arid", fos: "adj.", def: "lacking sufficient water or rainfall."},
    {word: "distinct", fos: "adj.", def: "constituting a separate entity or part."},
    {word: "graze", fos: "v.", def: "feed as in a meadow or pasture."},
    {word: "hectic", fos: "adj.", def: "marked by intense activity or agitation."},
    {word: "horde", fos: "n.", def: "a vast multitude."},
    {word: "humid", fos: "adj.", def: "containing or characterized by a great deal of water vapor."},
    {word: "incredible", fos: "adj.", def: "amazing; extraordinarily good or great."},
    {word: "inhabit", fos: "v.", def: "live in; be a resident of."},
    {word: "peninsula", fos: "n.", def: "a large mass of land projecting into a body of water."},
    {word: "rural", fos: "adj.", def: "living in or characteristic of farming or country life."},
    {word: "sanctuary", fos: "n.", def: "a consecrated place where sacred objects are kept."},
    {word: "splendor", fos: "n.", def: "the quality of being magnificent or grand."},
    {word: "squalor", fos: "n.", def: "sordid dirtiness."},
    {word: "terrain", fos: "n.", def: "a piece of ground having specific characteristics."},
    {word: "aloft", fos: "adv.", def: "at or on or to the masthead or upper rigging of a ship."},
    {word: "attain", fos: "v.", def: "gain with effort."},
    {word: "buffet", fos: "n.", def: "piece of furniture that stands at the side of a dining room."},
    {word: "elude", fos: "v.", def: "escape, either physically or mentally."},
    {word: "flammable", fos: "adj.", def: "easily ignited."},
    {word: "hover", fos: "v.", def: "hang in the air; fly or be suspended above."},
    {word: "inflate", fos: "v.", def: "fill with gas or air."},
    {word: "jeopardy", fos: "n.", def: "a source of danger."},
    {word: "moor", fos: "v.", def: "come into or dock at a wharf."},
    {word: "plummet", fos: "v.", def: "drop sharply."},
    {word: "pollute", fos: "v.", def: "contaminate; make impure."},
    {word: "propel", fos: "v.", def: "cause to move forward with force."},
    {word: "stationary", fos: "adj.", def: "not capable of being moved."},
    {word: "superb", fos: "adj.", def: "surpassingly good."},
    {word: "swivel", fos: "v.", def: "turn on a pivot."},
    {word: "antic", fos: "adj.", def: "ludicrously odd."},
    {word: "attire", fos: "n.", def: "clothing of a distinctive style or for a particular occasion."},
    {word: "captivate", fos: "v.", def: "attract; cause to be enamored."},
    {word: "deft", fos: "adj.", def: "skillful in physical movements; especially of the hands."},
    {word: "diligent", fos: "adj.", def: "quietly and steadily persevering in detail or exactness."},
    {word: "eclipse", fos: "n.", def: "the phenomenon when one celestial body obscures another."},
    {word: "evolve", fos: "v.", def: "undergo development."},
    {word: "innate", fos: "adj.", def: "present at birth but not necessarily hereditary."},
    {word: "inscribe", fos: "v.", def: "carve, cut, or etch into a material or surface."},
    {word: "posture", fos: "n.", def: "the arrangement of the body and its limbs."},
    {word: "shroud", fos: "n.", def: "burial garment in which a corpse is wrapped."},
    {word: "stifle", fos: "v.", def: "impair the respiration of or obstruct the air passage of."},
    {word: "tentative", fos: "adj.", def: "hesitant or lacking confidence; unsettled in mind or opinion."},
    {word: "tranquil", fos: "adj.", def: "free from disturbance by heavy waves."},
    {word: "versatile", fos: "adj.", def: "having great diversity or variety."},
    {word: "apparel", fos: "n.", def: "clothing in general."},
    {word: "appreciate", fos: "v.", def: "be fully aware of; realize fully."},
    {word: "continuous", fos: "adj.", def: "moving in time or space without interruption."},
    {word: "dissolve", fos: "v.", def: "pass into a solution."},
    {word: "domesticate", fos: "v.", def: "make fit for cultivation and service to humans."},
    {word: "emerge", fos: "v.", def: "come out into view, as from concealment."},
    {word: "fiber", fos: "n.", def: "a slender and elongated substance that can be spun into yarn."},
    {word: "function", fos: "n.", def: "what something is used for."},
    {word: "hatch", fos: "n.", def: "a movable barrier covering an entrance."},
    {word: "inhibit", fos: "v.", def: "limit the range or extent of."},
    {word: "minute", fos: "n.", def: "a unit of time equal to 60 seconds or 1/60th of an hour."},
    {word: "motion", fos: "n.", def: "the act of changing location from one place to another."},
    {word: "sheathe", fos: "v.", def: "enclose with a protective covering."},
    {word: "shed", fos: "v.", def: "cause or allow to flow or run out or over."},
    {word: "transfer", fos: "v.", def: "move from one place to another."},
    {word: "brawl", fos: "v.", def: "quarrel or fight noisily, angrily or disruptively."},
    {word: "casual", fos: "adj.", def: "without or seeming to be without plan or method; offhand."},
    {word: "constant", fos: "adj.", def: "uninterrupted in time and indefinitely long continuing."},
    {word: "excel", fos: "v.", def: "distinguish oneself."},
    {word: "exhaust", fos: "v.", def: "wear out completely."},
    {word: "hardy", fos: "adj.", def: "having rugged physical strength."},
    {word: "mediocre", fos: "adj.", def: "moderate to inferior in quality."},
    {word: "monotonous", fos: "adj.", def: "sounded or spoken in a tone unvarying in pitch."},
    {word: "originate", fos: "v.", def: "come into existence; take on form or shape."},
    {word: "punctuate", fos: "v.", def: "insert marks to clarify meaning."},
    {word: "ravenous", fos: "adj.", def: "extremely hungry."},
    {word: "realistic", fos: "adj.", def: "aware or expressing awareness of things as they are."},
    {word: "soothe", fos: "v.", def: "cause to feel better."},
    {word: "stampede", fos: "n.", def: "a wild headlong rush of frightened animals."},
    {word: "veteran", fos: "n.", def: "a person who has served in the armed forces."},
    {word: "accompany", fos: "v.", def: "go or travel along with."},
    {word: "beneficial", fos: "adj.", def: "promoting or enhancing well-being."},
    {word: "captive", fos: "n.", def: "a person who is confined; especially a prisoner of war."},
    {word: "convenient", fos: "adj.", def: "suited to your comfort or purpose or needs."},
    {word: "ecstasy", fos: "n.", def: "a state of elated bliss."},
    {word: "expanse", fos: "n.", def: "a wide and open space or area, as of land, sea, or sky."},
    {word: "expedition", fos: "n.", def: "an organized group of people undertaking a journey."},
    {word: "inept", fos: "adj.", def: "generally incompetent and ineffectual."},
    {word: "interpret", fos: "v.", def: "make sense of; assign a meaning to."},
    {word: "invaluable", fos: "adj.", def: "having incalculable monetary or intellectual worth."},
    {word: "linger", fos: "v.", def: "remain present although waning or gradually dying."},
    {word: "retrieve", fos: "v.", def: "get or find back; recover the use of."},
    {word: "skirmish", fos: "n.", def: "a minor short-term fight."},
    {word: "supplement", fos: "n.", def: "an additional component that improves capability."},
    {word: "territory", fos: "n.", def: "a region marked off for administrative or other purposes."},
    {word: "accumulate", fos: "v.", def: "get or gather together."},
    {word: "aggravate", fos: "v.", def: "make worse."},
    {word: "conserve", fos: "v.", def: "keep in safety and protect from harm, loss, or destruction."},
    {word: "contaminate", fos: "v.", def: "make impure."},
    {word: "diminish", fos: "v.", def: "decrease in size, extent, or range."},
    {word: "drastic", fos: "adj.", def: "forceful and extreme and rigorous."},
    {word: "extravagant", fos: "adj.", def: "recklessly wasteful."},
    {word: "frugal", fos: "adj.", def: "avoiding waste."},
    {word: "impurity", fos: "n.", def: "the condition of having extraneous elements."},
    {word: "peril", fos: "n.", def: "a state of danger involving risk."},
    {word: "perpetual", fos: "adj.", def: "continuing forever or indefinitely."},
    {word: "resource", fos: "n.", def: "aid or support that may be drawn upon when needed."},
    {word: "substitute", fos: "n.", def: "a person or thing that can take the place of another."},
    {word: "sustain", fos: "v.", def: "lengthen or extend in duration or space."},
    {word: "vital", fos: "adj.", def: "performing an essential function in the living body."},
    {word: "anticipate", fos: "v.", def: "regard something as probable or likely."},
    {word: "bankrupt", fos: "adj.", def: "financially ruined."},
    {word: "brief", fos: "adj.", def: "of short duration or distance."},
    {word: "brisk", fos: "adj.", def: "quick and energetic."},
    {word: "budget", fos: "n.", def: "a summary of intended expenditures."},
    {word: "compete", fos: "v.", def: "engage in a contest or measure oneself against others."},
    {word: "complicate", fos: "v.", def: "make less simple."},
    {word: "effect", fos: "n.", def: "a phenomenon that is caused by some previous phenomenon."},
    {word: "err", fos: "v.", def: "make a mistake."},
    {word: "factor", fos: "n.", def: "anything that contributes causally to a result."},
    {word: "fad", fos: "n.", def: "an interest followed with exaggerated zeal."},
    {word: "gripe", fos: "v.", def: "complain."},
    {word: "knack", fos: "n.", def: "a special way of doing something."},
    {word: "leisure", fos: "n.", def: "time available for ease and relaxation."},
    {word: "unique", fos: "adj.", def: "the single one of its kind."},
    {word: "abbreviate", fos: "v.", def: "shorten."},
    {word: "appropriate", fos: "adj.", def: "suitable for a particular person, place, or situation."},
    {word: "exclude", fos: "v.", def: "prevent from entering; shut out."},
    {word: "fanciful", fos: "adj.", def: "indulging in or influenced by the imagination."},
    {word: "futile", fos: "adj.", def: "producing no result or effect."},
    {word: "grudge", fos: "n.", def: "a resentment strong enough to justify retaliation."},
    {word: "inspire", fos: "v.", def: "serve as the inciting cause of."},
    {word: "majority", fos: "n.", def: "the main part."},
    {word: "persevere", fos: "v.", def: "be persistent, refuse to stop."},
    {word: "possess", fos: "v.", def: "have ownership of."},
    {word: "prejudice", fos: "n.", def: "a partiality preventing objective consideration of an issue."},
    {word: "resolute", fos: "adj.", def: "firm in purpose or belief."},
    {word: "sneer", fos: "n.", def: "a facial expression of contempt or scorn."},
    {word: "unanimous", fos: "adj.", def: "in complete agreement."},
    {word: "unruly", fos: "adj.", def: "unable to be governed or controlled."},
    {word: "abandon", fos: "v.", def: "forsake; leave behind."},
    {word: "adversary", fos: "n.", def: "someone who offers opposition."},
    {word: "baffle", fos: "v.", def: "be a mystery or bewildering to."},
    {word: "blunder", fos: "n.", def: "an embarrassing mistake."},
    {word: "colossal", fos: "adj.", def: "so great in size or force or extent as to elicit awe."},
    {word: "detect", fos: "v.", def: "discover or determine the existence, presence, or fact of."},
    {word: "haul", fos: "v.", def: "draw slowly or heavily."},
    {word: "overpower", fos: "v.", def: "defeat by superior force."},
    {word: "rejoice", fos: "v.", def: "feel happiness."},
    {word: "scoff", fos: "v.", def: "laugh at with contempt and derision."},
    {word: "sentinel", fos: "n.", def: "a person employed to keep watch for some anticipated event."},
    {word: "siege", fos: "n.", def: "an action of an armed force that surrounds a fortified place."},
    {word: "sinister", fos: "adj.", def: "wicked, evil, or dishonorable."},
    {word: "victor", fos: "n.", def: "a combatant who is able to defeat rivals."},
    {word: "woe", fos: "n.", def: "misery resulting from affliction."},
    {word: "adapt", fos: "v.", def: "make fit for, or change to suit a new purpose."},
    {word: "deplete", fos: "v.", def: "use up, as resources or materials."},
    {word: "efficient", fos: "adj.", def: "being effective without wasting time, effort, or expense."},
    {word: "fatigue", fos: "n.", def: "temporary loss of strength and energy from hard work."},
    {word: "gait", fos: "n.", def: "an animal's manner of moving."},
    {word: "glare", fos: "v.", def: "be sharply reflected."},
    {word: "habitat", fos: "n.", def: "the type of environment in which an organism normally lives."},
    {word: "oblivious", fos: "adj.", def: "lacking conscious awareness of."},
    {word: "outmoded", fos: "adj.", def: "no longer in fashion."},
    {word: "prominent", fos: "adj.", def: "conspicuous in position or importance."},
    {word: "quench", fos: "v.", def: "satisfy, as thirst."},
    {word: "rigor", fos: "n.", def: "excessive sternness."},
    {word: "sear", fos: "v.", def: "become superficially burned (also figurative)."},
    {word: "transport", fos: "v.", def: "move something or somebody around."},
    {word: "wend", fos: "v.", def: "direct one's course or way."},
    {word: "benevolent", fos: "adj.", def: "showing or motivated by sympathy and understanding."},
    {word: "consent", fos: "v.", def: "give an affirmative reply to; respond favorably to."},
    {word: "discreet", fos: "adj.", def: "marked by prudence or modesty and wise self-restraint."},
    {word: "engross", fos: "v.", def: "devote fully to."},
    {word: "esteem", fos: "n.", def: "the condition of being honored."},
    {word: "exaggerate", fos: "v.", def: "enlarge beyond bounds or the truth."},
    {word: "extensive", fos: "adj.", def: "large in spatial extent or range or scope or quantity."},
    {word: "fantastic", fos: "adj.", def: "extravagantly fanciful in design, construction, appearance."},
    {word: "intrigue", fos: "n.", def: "a crafty and involved plot to achieve your ends."},
    {word: "marvel", fos: "v.", def: "be amazed at."},
    {word: "mission", fos: "n.", def: "an operation that is assigned by a higher headquarters."},
    {word: "opportunity", fos: "n.", def: "a possibility from a favorable combination of circumstances."},
    {word: "relinquish", fos: "v.", def: "turn away from; give up."},
    {word: "tyrant", fos: "n.", def: "a cruel and oppressive dictator."},
    {word: "vanquish", fos: "v.", def: "defeat in a competition, race, or conflict."},
    {word: "analyze", fos: "v.", def: "break down into components or essential features."},
    {word: "apprehensive", fos: "adj.", def: "in fear or dread of possible evil or harm."},
    {word: "coincide", fos: "v.", def: "happen simultaneously."},
    {word: "compose", fos: "v.", def: "form the substance of."},
    {word: "disk", fos: "n.", def: "something with a flat round shape."},
    {word: "envelop", fos: "v.", def: "enclose or enfold completely with or as if with a covering."},
    {word: "exist", fos: "v.", def: "have a presence."},
    {word: "extraordinary", fos: "adj.", def: "highly unusual or exceptional or remarkable."},
    {word: "fuse", fos: "n.", def: "any igniter used to initiate the burning of a propellant."},
    {word: "mere", fos: "adj.", def: "being nothing more than specified."},
    {word: "revolve", fos: "v.", def: "turn on or around an axis or a center."},
    {word: "scale", fos: "n.", def: "an ordered reference standard."},
    {word: "solar", fos: "adj.", def: "relating to the sun or utilizing the energies of the sun."},
    {word: "trace", fos: "n.", def: "an indication that something has been present."},
    {word: "velocity", fos: "n.", def: "distance traveled per unit time in one direction."},
    {word: "awe", fos: "n.", def: "an overwhelming feeling of wonder or admiration."},
    {word: "catastrophe", fos: "n.", def: "a sudden violent change in the earth's surface."},
    {word: "collide", fos: "v.", def: "crash together with violent impact."},
    {word: "consequence", fos: "n.", def: "a phenomenon that is caused by some previous phenomenon."},
    {word: "deceive", fos: "v.", def: "cause someone to believe an untruth."},
    {word: "fatality", fos: "n.", def: "the quality of being able to cause death."},
    {word: "improvise", fos: "v.", def: "manage in a makeshift way; do with whatever is at hand."},
    {word: "loom", fos: "n.", def: "a textile machine for weaving yarn into a textile."},
    {word: "lull", fos: "v.", def: "make calm or still."},
    {word: "placid", fos: "adj.", def: "calm and free from disturbance."},
    {word: "predicament", fos: "n.", def: "an unpleasant or difficult situation."},
    {word: "priority", fos: "n.", def: "status established in order of importance or urgency."},
    {word: "reinforce", fos: "v.", def: "strengthen and support."},
    {word: "stern", fos: "adj.", def: "serious and harsh in manner or behavior."},
    {word: "treacherous", fos: "adj.", def: "dangerously unstable and unpredictable."},
    {word: "corrode", fos: "v.", def: "cause to deteriorate due to water, air, or an acid."},
    {word: "debris", fos: "n.", def: "the remains of something that has been destroyed."},
    {word: "elated", fos: "adj.", def: "exultantly proud and joyful; in high spirits."},
    {word: "exploit", fos: "v.", def: "use or manipulate to one's advantage."},
    {word: "leeway", fos: "n.", def: "a permissible difference."},
    {word: "miniature", fos: "adj.", def: "being on a very small scale."},
    {word: "mobile", fos: "adj.", def: "moving or capable of moving readily."},
    {word: "onset", fos: "n.", def: "the beginning or early stages."},
    {word: "ooze", fos: "v.", def: "pass gradually or leak or as if through small openings."},
    {word: "pathetic", fos: "adj.", def: "deserving or inciting pity."},
    {word: "preliminary", fos: "adj.", def: "preceding or in preparation for something more important."},
    {word: "quest", fos: "n.", def: "the act of searching for something."},
    {word: "restrain", fos: "v.", def: "hold back."},
    {word: "salvage", fos: "n.", def: "rescuing a ship or its crew from a shipwreck or a fire."},
    {word: "scour", fos: "v.", def: "rub hard or scrub."},
    {word: "abroad", fos: "adv.", def: "to or in a foreign country."},
    {word: "anguish", fos: "n.", def: "extreme distress of body or mind."},
    {word: "commence", fos: "v.", def: "set in motion, cause to start."},
    {word: "commend", fos: "v.", def: "present as worthy of regard, kindness, or confidence."},
    {word: "controversy", fos: "n.", def: "a dispute where there is strong disagreement."},
    {word: "cordial", fos: "adj.", def: "politely warm and friendly."},
    {word: "dissent", fos: "n.", def: "a difference of opinion."},
    {word: "earnest", fos: "adj.", def: "characterized by a firm, sincere belief in one's opinions."},
    {word: "elicit", fos: "v.", def: "call forth, as an emotion, feeling, or response."},
    {word: "exhilaration", fos: "n.", def: "the feeling of lively and cheerful joy."},
    {word: "genuine", fos: "adj.", def: "not fake or counterfeit."},
    {word: "hoax", fos: "n.", def: "something intended to deceive."},
    {word: "manipulate", fos: "v.", def: "influence or control shrewdly or deviously."},
    {word: "recount", fos: "v.", def: "narrate or give a detailed account of."},
    {word: "skeptic", fos: "n.", def: "someone who habitually doubts accepted beliefs."},
    {word: "breach", fos: "n.", def: "an opening, especially a gap in a dike or fortification."},
    {word: "clammy", fos: "adj.", def: "unpleasantly cool and humid."},
    {word: "construct", fos: "v.", def: "make by combining materials and parts."},
    {word: "elaborate", fos: "adj.", def: "marked by complexity and richness of detail."},
    {word: "fragrant", fos: "adj.", def: "pleasant-smelling."},
    {word: "furnish", fos: "v.", def: "provide with objects or articles that make a room usable."},
    {word: "haven", fos: "n.", def: "a sheltered port where ships can take on or discharge cargo."},
    {word: "install", fos: "v.", def: "set up for use."},
    {word: "massive", fos: "adj.", def: "containing a great quantity of matter."},
    {word: "repel", fos: "v.", def: "force or drive back."},
    {word: "restore", fos: "v.", def: "bring back into original existence, function, or position."},
    {word: "retaliate", fos: "v.", def: "make a counterattack and return like for like."},
    {word: "stench", fos: "n.", def: "a distinctive odor that is offensively unpleasant."},
    {word: "strew", fos: "v.", def: "spread by scattering."},
    {word: "vicinity", fos: "n.", def: "a surrounding or nearby region."},
    {word: "bluster", fos: "v.", def: "be gusty, as of wind."},
    {word: "council", fos: "n.", def: "a body serving in an administrative capacity."},
    {word: "dwell", fos: "v.", def: "inhabit or live in."},
    {word: "exterminate", fos: "v.", def: "kill on a large scale."},
    {word: "fee", fos: "n.", def: "a fixed charge for a privilege or for professional services."},
    {word: "garment", fos: "n.", def: "an article of clothing."},
    {word: "infest", fos: "v.", def: "occupy in large numbers or live on a host."},
    {word: "insist", fos: "v.", def: "be emphatic or resolute and refuse to budge."},
    {word: "paltry", fos: "adj.", def: "contemptibly small in amount or size."},
    {word: "peculiar", fos: "adj.", def: "beyond or deviating from the usual or expected."},
    {word: "rash", fos: "adj.", def: "imprudently incurring risk."},
    {word: "revenge", fos: "n.", def: "action taken in return for an injury or offense."},
    {word: "rodent", fos: "n.", def: "a mammal having two pairs of ever-growing front teeth for gnawing."},
    {word: "swarm", fos: "n.", def: "a group of many things in the air or on the ground."},
    {word: "vat", fos: "n.", def: "a large open vessel for holding or storing liquids."},
    {word: "accustom", fos: "v.", def: "familiarize psychologically or physically."},
    {word: "alert", fos: "v.", def: "warn or arouse to a sense of danger."},
    {word: "assign", fos: "v.", def: "select something or someone for a specific purpose."},
    {word: "budge", fos: "v.", def: "move very slightly."},
    {word: "burly", fos: "adj.", def: "muscular and heavily built."},
    {word: "companion", fos: "n.", def: "a friend who is frequently with another."},
    {word: "compatible", fos: "adj.", def: "able to exist and perform in harmonious combination."},
    {word: "concept", fos: "n.", def: "an abstract or general idea inferred from specific instances."},
    {word: "distract", fos: "v.", def: "draw someone's attention away from something."},
    {word: "jostle", fos: "v.", def: "make one's way by pushing or shoving."},
    {word: "obedient", fos: "adj.", def: "dutifully complying with the commands of those in authority."},
    {word: "obstacle", fos: "n.", def: "something that stands in the way and must be surmounted."},
    {word: "patient", fos: "adj.", def: "enduring trying circumstances with even temper."},
    {word: "pedestrian", fos: "n.", def: "a person who travels by foot."},
    {word: "retire", fos: "v.", def: "withdraw from active participation."},
    {word: "aroma", fos: "n.", def: "any property detected by the sense of smell."},
    {word: "beverage", fos: "n.", def: "any liquid suitable for drinking."},
    {word: "bland", fos: "adj.", def: "lacking taste or flavor or tang."},
    {word: "brittle", fos: "adj.", def: "having little elasticity."},
    {word: "cluster", fos: "n.", def: "a grouping of a number of similar things."},
    {word: "combine", fos: "v.", def: "put or add together."},
    {word: "consume", fos: "v.", def: "take in as food."},
    {word: "crave", fos: "v.", def: "have an appetite or great desire for."},
    {word: "cultivate", fos: "v.", def: "adapt something wild to the environment."},
    {word: "equivalent", fos: "adj.", def: "being essentially comparable to something."},
    {word: "export", fos: "v.", def: "sell or transfer abroad."},
    {word: "extract", fos: "v.", def: "remove, usually with some force or effort."},
    {word: "introduce", fos: "v.", def: "bring something new to an environment."},
    {word: "purchase", fos: "v.", def: "acquire by means of a financial transaction."},
    {word: "tropical", fos: "adj.", def: "relating to part of the Earth's surface with hot climate."},
    {word: "ancestor", fos: "n.", def: "someone from whom you are descended."},
    {word: "carnivore", fos: "n.", def: "a terrestrial or aquatic flesh-eating mammal."},
    {word: "comprehend", fos: "v.", def: "get the meaning of something."},
    {word: "duration", fos: "n.", def: "the period of time during which something continues."},
    {word: "evident", fos: "adj.", def: "clearly revealed to the mind or the senses or judgment."},
    {word: "extinct", fos: "adj.", def: "no longer in existence."},
    {word: "ferocious", fos: "adj.", def: "marked by extreme and violent energy."},
    {word: "gigantic", fos: "adj.", def: "exceedingly large or extensive."},
    {word: "obscure", fos: "adj.", def: "not clearly understood or expressed."},
    {word: "option", fos: "n.", def: "one of a number of things from which only one can be chosen."},
    {word: "premature", fos: "adj.", def: "too soon or too hasty."},
    {word: "preserve", fos: "v.", def: "keep in safety and protect from harm, loss, or destruction."},
    {word: "prey", fos: "n.", def: "animal hunted or caught for food."},
    {word: "puny", fos: "adj.", def: "of inferior size."},
    {word: "survive", fos: "v.", def: "continue in existence after."},
    {word: "accurate", fos: "adj.", def: "characterized by perfect conformity to fact or truth."},
    {word: "approximate", fos: "adj.", def: "not quite exact or correct."},
    {word: "course", fos: "n.", def: "a connected series of events or actions or developments."},
    {word: "depart", fos: "v.", def: "go away or leave."},
    {word: "despair", fos: "n.", def: "a state in which all hope is lost or absent."},
    {word: "destination", fos: "n.", def: "the place designated as the end, as of a race or journey."},
    {word: "deteriorate", fos: "v.", def: "become worse or disintegrate."},
    {word: "gale", fos: "n.", def: "a strong wind moving 34–40 knots."},
    {word: "horizon", fos: "n.", def: "the line at which the sky and Earth appear to meet."},
    {word: "jubilation", fos: "n.", def: "a feeling of extreme joy."},
    {word: "navigate", fos: "v.", def: "direct carefully and safely."},
    {word: "nostalgia", fos: "n.", def: "a longing for something past."},
    {word: "revive", fos: "v.", def: "cause to regain consciousness."},
    {word: "sever", fos: "v.", def: "set or keep apart."},
    {word: "voyage", fos: "n.", def: "a journey to some distant place."},
    {word: "avalanche", fos: "n.", def: "a slide of large masses of snow, ice and mud down a mountain."},
    {word: "blizzard", fos: "n.", def: "a weather event with widespread snowfall and strong winds."},
    {word: "challenge", fos: "n.", def: "a call to engage in a contest or fight."},
    {word: "conquer", fos: "v.", def: "take possession of by force, as after an invasion."},
    {word: "crevice", fos: "n.", def: "a long narrow opening."},
    {word: "foolhardy", fos: "adj.", def: "marked by defiant disregard for danger or consequences."},
    {word: "lure", fos: "v.", def: "provoke someone to do something through persuasion."},
    {word: "makeshift", fos: "adj.", def: "done or made using whatever is available."},
    {word: "optimist", fos: "n.", def: "a person disposed to take a favorable view of things."},
    {word: "previous", fos: "adj.", def: "just preceding something else in time or order."},
    {word: "route", fos: "n.", def: "an established line of travel or access."},
    {word: "summit", fos: "n.", def: "the top or extreme point of something."},
    {word: "terse", fos: "adj.", def: "brief and to the point."},
    {word: "thwart", fos: "v.", def: "hinder or prevent, as an effort, plan, or desire."},
    {word: "vertical", fos: "adj.", def: "at right angles to the plane of the horizon or a base line."},
    {word: "abolish", fos: "v.", def: "do away with."},
    {word: "agony", fos: "n.", def: "intense feelings of suffering; acute mental or physical pain."},
    {word: "catapult", fos: "n.", def: "an engine providing medieval artillery used during sieges."},
    {word: "character", fos: "n.", def: "a property that defines the individual nature of something."},
    {word: "denounce", fos: "v.", def: "speak out against."},
    {word: "escalate", fos: "v.", def: "increase in extent or intensity."},
    {word: "grim", fos: "adj.", def: "harshly uninviting or formidable in manner or appearance."},
    {word: "harbor", fos: "n.", def: "a sheltered port where ships can take on or discharge cargo."},
    {word: "inflict", fos: "v.", def: "impose something unpleasant."},
    {word: "loathe", fos: "v.", def: "dislike intensely; feel disgust toward."},
    {word: "meddle", fos: "v.", def: "intrude in other people's affairs or business."},
    {word: "monstrous", fos: "adj.", def: "distorted and unnatural in shape or size."},
    {word: "rouse", fos: "v.", def: "cause to become awake or conscious."},
    {word: "steadfast", fos: "adj.", def: "marked by firm determination or resolution; not shakable."},
    {word: "translate", fos: "v.", def: "restate from one language into another language."},
    {word: "colony", fos: "n.", def: "a group of organisms of the same type living together."},
    {word: "compensate", fos: "v.", def: "make amends for."},
    {word: "deposit", fos: "n.", def: "the act of putting something somewhere."},
    {word: "fascinate", fos: "v.", def: "attract; cause to be enamored."},
    {word: "feeble", fos: "adj.", def: "pathetically lacking in force or effectiveness."},
    {word: "formal", fos: "adj.", def: "in accord with established conventions and requirements."},
    {word: "frigid", fos: "adj.", def: "extremely cold."},
    {word: "harsh", fos: "adj.", def: "disagreeable to the senses."},
    {word: "huddle", fos: "n.", def: "a disorganized and densely packed crowd."},
    {word: "remote", fos: "adj.", def: "located far away spatially."},
    {word: "resemble", fos: "v.", def: "be similar or bear a likeness to."},
    {word: "rigid", fos: "adj.", def: "incapable of or resistant to bending."},
    {word: "solitary", fos: "adj.", def: "not growing or living in groups or colonies."},
    {word: "substantial", fos: "adj.", def: "real; having a material or factual existence."},
    {word: "waddle", fos: "v.", def: "walk unsteadily."},
    {word: "assemble", fos: "v.", def: "create by putting components or members together."},
    {word: "banquet", fos: "n.", def: "a ceremonial dinner party for many people."},
    {word: "cargo", fos: "n.", def: "goods carried by a large vehicle."},
    {word: "cask", fos: "n.", def: "a cylindrical container that holds liquids."},
    {word: "celebrate", fos: "v.", def: "have a festivity."},
    {word: "decrease", fos: "n.", def: "a change downward."},
    {word: "desperate", fos: "n.", def: "a person who is frightened and in need of help."},
    {word: "edible", fos: "adj.", def: "suitable for use as food."},
    {word: "frivolous", fos: "adj.", def: "not serious in content, attitude, or behavior."},
    {word: "harvest", fos: "n.", def: "the gathering of a ripened crop."},
    {word: "hew", fos: "v.", def: "make or shape as with an axe."},
    {word: "hostile", fos: "adj.", def: "characterized by enmity or ill will."},
    {word: "pledge", fos: "n.", def: "a binding commitment to do or give or refrain from something."},
    {word: "prosper", fos: "v.", def: "make steady progress."},
    {word: "task", fos: "n.", def: "any piece of work that is undertaken or attempted."},
    {word: "absurd", fos: "adj.", def: "inconsistent with reason or logic or common sense."},
    {word: "accomplish", fos: "v.", def: "achieve with effort."},
    {word: "ascend", fos: "v.", def: "travel up."},
    {word: "dense", fos: "adj.", def: "having high compaction or concentration."},
    {word: "experiment", fos: "n.", def: "the act of conducting a controlled test or investigation."},
    {word: "flimsy", fos: "n.", def: "a thin strong lightweight translucent paper."},
    {word: "heroic", fos: "adj.", def: "having qualities appropriate for brave figures."},
    {word: "lumber", fos: "n.", def: "the wood of trees prepared for use as building material."},
    {word: "mimic", fos: "v.", def: "imitate, especially for satirical effect."},
    {word: "significant", fos: "adj.", def: "rich in implication."},
    {word: "soar", fos: "v.", def: "rise rapidly."},
    {word: "spectator", fos: "n.", def: "a close observer; someone who looks at something."},
    {word: "suspend", fos: "v.", def: "bar temporarily."},
    {word: "terminate", fos: "v.", def: "bring to an end or halt."},
    {word: "unwieldy", fos: "adj.", def: "difficult to use or handle because of size or weight."},
    {word: "available", fos: "adj.", def: "obtainable or accessible and ready for use or service."},
    {word: "bondage", fos: "n.", def: "the state of being under the control of another person."},
    {word: "donate", fos: "v.", def: "give to a charity or good cause."},
    {word: "establish", fos: "v.", def: "set up or found."},
    {word: "evade", fos: "v.", def: "avoid or try to avoid fulfilling, answering, or performing."},
    {word: "liberate", fos: "v.", def: "grant freedom to; free from confinement."},
    {word: "numerous", fos: "adj.", def: "amounting to a large indefinite number."},
    {word: "occasion", fos: "n.", def: "an event that occurs at a critical time."},
    {word: "oppose", fos: "v.", def: "be against."},
    {word: "prohibit", fos: "v.", def: "command against."},
    {word: "pursue", fos: "v.", def: "follow in an effort to capture."},
    {word: "reassure", fos: "v.", def: "cause to feel confident."},
    {word: "reluctant", fos: "adj.", def: "not eager."},
    {word: "superior", fos: "adj.", def: "of high quality or performance."},
    {word: "yearn", fos: "v.", def: "desire strongly or persistently."},
    {word: "accelerate", fos: "v.", def: "move faster."},
    {word: "altitude", fos: "n.", def: "elevation above sea level or above the earth's surface."},
    {word: "anxious", fos: "adj.", def: "causing or fraught with or showing nervousness."},
    {word: "brace", fos: "n.", def: "a support that steadies or strengthens something else."},
    {word: "confident", fos: "adj.", def: "having or marked by assurance."},
    {word: "contact", fos: "n.", def: "the act of touching physically."},
    {word: "exult", fos: "v.", def: "feel extreme happiness or elation."},
    {word: "hangar", fos: "n.", def: "a structure where aircraft can be stored and maintained."},
    {word: "maximum", fos: "adj.", def: "the greatest or most complete or best possible."},
    {word: "methodical", fos: "adj.", def: "characterized by orderliness."},
    {word: "nonchalant", fos: "adj.", def: "marked by casual unconcern or indifference."},
    {word: "proceed", fos: "v.", def: "move ahead; travel onward in time or space."},
    {word: "saunter", fos: "v.", def: "walk leisurely and with no apparent aim."},
    {word: "solo", fos: "n.", def: "any activity that is performed alone without assistance."},
    {word: "stall", fos: "n.", def: "a small area set off for special use."},
    {word: "convalesce", fos: "v.", def: "get over an illness or shock."},
    {word: "dedicate", fos: "v.", def: "give entirely to a specific person, activity, or cause."},
    {word: "dictate", fos: "n.", def: "a guiding principle."},
    {word: "exasperate", fos: "v.", def: "make furious."},
    {word: "notable", fos: "adj.", def: "worthy of attention or interest."},
    {word: "overdue", fos: "adj.", def: "not paid at the scheduled time."},
    {word: "overthrow", fos: "v.", def: "reject or overturn a decision or an argument."},
    {word: "penetrate", fos: "v.", def: "pass into or through, often by overcoming resistance."},
    {word: "portrait", fos: "n.", def: "any likeness of a person, in any medium."},
    {word: "rebel", fos: "n.", def: "someone who exhibits independence in thought and action."},
    {word: "restrict", fos: "v.", def: "limit access to."},
    {word: "seldom", fos: "adv.", def: "not often."},
    {word: "stimulate", fos: "v.", def: "cause to act in a specified manner."},
    {word: "tempest", fos: "n.", def: "a violent commotion or disturbance."},
    {word: "upbringing", fos: "n.", def: "helping someone grow up to be a member of the community."},
    {word: "accommodate", fos: "v.", def: "have room for; hold without crowding."},
    {word: "aggressive", fos: "adj.", def: "characteristic of an enemy or one eager to fight."},
    {word: "bask", fos: "v.", def: "expose oneself to warmth and light, as for relaxation."},
    {word: "carcass", fos: "n.", def: "the dead body of an animal."},
    {word: "conceal", fos: "v.", def: "prevent from being seen or discovered."},
    {word: "flail", fos: "n.", def: "an implement with a handle and a free swinging stick."},
    {word: "gorge", fos: "n.", def: "a deep ravine, usually with a river running through it."},
    {word: "morsel", fos: "n.", def: "a small amount of solid food; a mouthful."},
    {word: "protrude", fos: "v.", def: "extend out or project in space."},
    {word: "ripple", fos: "n.", def: "a small wave on the surface of a liquid."},
    {word: "slither", fos: "v.", def: "pass or move unobtrusively or smoothly."},
    {word: "sluggish", fos: "adj.", def: "moving slowly."},
    {word: "snout", fos: "n.", def: "a long projecting or anterior elongation of an animal's head."},
    {word: "taper", fos: "v.", def: "diminish gradually."},
    {word: "visible", fos: "adj.", def: "capable of being seen or open to easy view."},
    {word: "access", fos: "n.", def: "the right to enter."},
    {word: "associate", fos: "v.", def: "bring or come into action."},
    {word: "boisterous", fos: "adj.", def: "marked by exuberance and high spirits."},
    {word: "brilliant", fos: "adj.", def: "full of light; shining intensely."},
    {word: "decade", fos: "n.", def: "a period of 10 years."},
    {word: "delicate", fos: "adj.", def: "developed with extreme subtlety."},
    {word: "employ", fos: "v.", def: "put into service."},
    {word: "idle", fos: "adj.", def: "not in action or at work."},
    {word: "illuminate", fos: "v.", def: "make lighter or brighter."},
    {word: "provide", fos: "v.", def: "give something useful or necessary to."},
    {word: "require", fos: "v.", def: "have need of."},
    {word: "taunt", fos: "v.", def: "harass with persistent criticism or carping."},
    {word: "tolerant", fos: "adj.", def: "showing or characterized by broad-mindedness."},
    {word: "transform", fos: "v.", def: "change or alter in appearance or nature."},
    {word: "wilderness", fos: "n.", def: "a wild and uninhabited area left in its natural condition."},
    {word: "disaster", fos: "n.", def: "an event resulting in great loss and misfortune."},
    {word: "flee", fos: "v.", def: "run away quickly."},
    {word: "fracture", fos: "n.", def: "breaking of hard tissue such as bone."},
    {word: "immense", fos: "adj.", def: "unusually great in size or amount or extent or scope."},
    {word: "intense", fos: "adj.", def: "possessing a distinctive feature to a heightened degree."},
    {word: "investigate", fos: "v.", def: "conduct an inquiry of."},
    {word: "lurch", fos: "v.", def: "move suddenly or as if unable to control one's movements."},
    {word: "major", fos: "adj.", def: "greater in scope or effect."},
    {word: "minor", fos: "adj.", def: "inferior in number or size or amount."},
    {word: "petrify", fos: "v.", def: "change into stone."},
    {word: "predict", fos: "v.", def: "make a guess about what will happen in the future."},
    {word: "prone", fos: "adj.", def: "having a tendency."},
    {word: "sparse", fos: "adj.", def: "not dense or plentiful."},
    {word: "topple", fos: "v.", def: "fall down, as if collapsing."},
    {word: "urban", fos: "adj.", def: "relating to a city or densely populated area."},
    {word: "abdicate", fos: "v.", def: "give up power, duties, or obligations."},
    {word: "assume", fos: "v.", def: "take to be the case or to be true."},
    {word: "bungle", fos: "v.", def: "make a mess of, destroy, or ruin."},
    {word: "dominate", fos: "v.", def: "be in control."},
    {word: "former", fos: "n.", def: "the first of two or the first mentioned of two."},
    {word: "guardian", fos: "n.", def: "a person who cares for persons or property."},
    {word: "hoist", fos: "v.", def: "raise or haul up with or as if with mechanical help."},
    {word: "intercept", fos: "v.", def: "seize, interrupt, or stop something on its way."},
    {word: "jubilee", fos: "n.", def: "a special anniversary or the celebration of it."},
    {word: "kin", fos: "n.", def: "a person related to another or others."},
    {word: "pardon", fos: "v.", def: "accept an excuse for."},
    {word: "proclaim", fos: "v.", def: "declare formally."},
    {word: "provoke", fos: "v.", def: "provide the needed stimulus for."},
    {word: "reign", fos: "n.", def: "royal authority; the dominion of a monarch."},
    {word: "riot", fos: "n.", def: "a state of disorder involving group violence."},
    {word: "afflict", fos: "v.", def: "cause physical pain or suffering in."},
    {word: "barren", fos: "adj.", def: "completely wanting or lacking."},
    {word: "consist", fos: "v.", def: "have its essential character."},
    {word: "drought", fos: "n.", def: "a shortage of rainfall."},
    {word: "erode", fos: "v.", def: "remove soil or rock."},
    {word: "expand", fos: "v.", def: "extend in one or more directions."},
    {word: "famine", fos: "n.", def: "a severe shortage of food resulting in starvation and death."},
    {word: "fertile", fos: "adj.", def: "capable of reproducing."},
    {word: "oasis", fos: "n.", def: "a shelter serving as a place of safety or sanctuary."},
    {word: "pasture", fos: "n.", def: "a field covered with grass and suitable for grazing."},
    {word: "primitive", fos: "adj.", def: "characteristic of an earlier ancestral type."},
    {word: "refuge", fos: "n.", def: "something or someone turned to for assistance or security."},
    {word: "revert", fos: "v.", def: "go back to a previous state."},
    {word: "teem", fos: "v.", def: "be full of or abuzz with."},
    {word: "wither", fos: "v.", def: "lose freshness, vigor, or vitality."},
    {word: "animated", fos: "adj.", def: "having life or vigor or spirit."},
    {word: "betray", fos: "v.", def: "deliver to an enemy by treachery."},
    {word: "convince", fos: "v.", def: "make realize the truth or validity of something."},
    {word: "decline", fos: "v.", def: "grow worse."},
    {word: "hilarious", fos: "adj.", def: "extremely funny; causing laughter."},
    {word: "likeness", fos: "n.", def: "similarity in appearance or nature between persons or things."},
    {word: "meager", fos: "adj.", def: "deficient in amount or quality or extent."},
    {word: "mischief", fos: "n.", def: "reckless or malicious behavior causing annoyance in others."},
    {word: "negotiate", fos: "v.", def: "discuss the terms of an arrangement."},
    {word: "obsolete", fos: "adj.", def: "no longer in use."},
    {word: "retain", fos: "v.", def: "secure and keep for possible future use or application."},
    {word: "sensation", fos: "n.", def: "an awareness of some type of stimulation."},
    {word: "somber", fos: "adj.", def: "serious and gloomy in character."},
    {word: "subsequent", fos: "adj.", def: "following in time or order."},
    {word: "vow", fos: "n.", def: "a solemn pledge to do something."},
    {word: "dormant", fos: "adj.", def: "inactive but capable of becoming active."},
    {word: "elegant", fos: "adj.", def: "refined and tasteful in appearance, behavior, or style."},
    {word: "erupt", fos: "v.", def: "start suddenly."},
    {word: "excavate", fos: "v.", def: "recover through digging."},
    {word: "expel", fos: "v.", def: "eliminate."},
    {word: "fume", fos: "n.", def: "a cloud of fine particles suspended in a gas."},
    {word: "molten", fos: "adj.", def: "reduced to liquid form by heating."},
    {word: "painstaking", fos: "adj.", def: "characterized by extreme care and great effort."},
    {word: "perish", fos: "v.", def: "pass from physical life."},
    {word: "population", fos: "n.", def: "the people who inhabit a territory or state."},
    {word: "prelude", fos: "n.", def: "something that introduces what follows."},
    {word: "scald", fos: "v.", def: "burn with a hot liquid or steam."},
    {word: "stupendous", fos: "adj.", def: "so great in size, force, or extent as to elicit awe."},
    {word: "suffocate", fos: "v.", def: "deprive of oxygen and prevent from breathing."},
    {word: "tremor", fos: "n.", def: "an involuntary vibration, as if from illness or fear."},
    {word: "ample", fos: "adj.", def: "more than enough in size or scope or capacity."},
    {word: "burden", fos: "n.", def: "weight to be carried or borne."},
    {word: "compassion", fos: "n.", def: "a deep awareness of and sympathy for another's suffering."},
    {word: "comply", fos: "v.", def: "act in accordance with someone's rules, commands, or wishes."},
    {word: "cumbersome", fos: "adj.", def: "difficult to handle or use, especially because of size or weight."},
    {word: "distress", fos: "n.", def: "a state of adversity."},
    {word: "encounter", fos: "v.", def: "come together."},
    {word: "exert", fos: "v.", def: "put to use."},
    {word: "indignant", fos: "adj.", def: "angered at something unjust or wrong."},
    {word: "jest", fos: "n.", def: "activity characterized by good humor."},
    {word: "mirth", fos: "n.", def: "great merriment."},
    {word: "moral", fos: "adj.", def: "concerned with principles of right and wrong."},
    {word: "outskirts", fos: "n.", def: "area relatively far from the center, as of a city or town."},
    {word: "resume", fos: "v.", def: "take up or begin anew."},
    {word: "ridicule", fos: "n.", def: "language or behavior intended to mock or humiliate."}
];
