export const words = [
    {word: "abate", fos: "v.", def: "To become weaker; to decrease."},
    {word: "acknowledge", fos: "v.", def: "To admit the existence of."},
    {word: "agent", fos: "n.", def: "A person who acts or does business for another."},
    {word: "authority", fos: "n.", def: "The right to give orders, make decisions, or take action."},
    {word: "devastate", fos: "v.", def: "To ruin or destroy completely."},
    {word: "epidemic", fos: "n.", def: "The rapid spreading of a disease to many people at one time."},
    {word: "estimate", fos: "n.", def: "A number that is not exact; a careful guess."},
    {word: "evict", fos: "v.", def: "To force out of property by taking legal action."},
    {word: "impartial", fos: "adj.", def: "Not favoring one side more than another; fair."},
    {word: "industrious", fos: "adj.", def: "Hardworking; not lazy."},
    {word: "infuriate", fos: "v.", def: "To make very angry."},
    {word: "irrelevant", fos: "adj.", def: "Having nothing to do with the subject."},
    {word: "precise", fos: "adj.", def: "Exact; specific."},
    {word: "sham", fos: "n.", def: "Something fake or false."},
    {word: "trek", fos: "n.", def: "A long, slow, and difficult journey."},
    {word: "astute", fos: "adj.", def: "Wise in a clever or practical way."},
    {word: "authentic", fos: "adj.", def: "Genuine; true."},
    {word: "delicacy", fos: "n.", def: "A choice item of food."},
    {word: "derogatory", fos: "adj.", def: "Expressing a low opinion; intended to hurt the reputation of a person or thing."},
    {word: "devour", fos: "v.", def: "To eat up hungrily."},
    {word: "figment", fos: "n.", def: "Something that is made up in the mind but that has no connection with reality."},
    {word: "mythical", fos: "adj.", def: "Imaginary; not real."},
    {word: "plumage", fos: "n.", def: "A bird's feathers."},
    {word: "predatory", fos: "adj.", def: "Living by killing and eating other animals."},
    {word: "prior", fos: "adj.", def: "Coming earlier in time."},
    {word: "scavenge", fos: "v.", def: "To search through and pick over, looking for something usable."},
    {word: "slaughter", fos: "v.", def: "To kill in order to obtain meat."},
    {word: "solitude", fos: "n.", def: "The condition of being alone or at some distance from people."},
    {word: "ungainly", fos: "adj.", def: "Moving in a clumsy or awkward way."},
    {word: "vulnerable", fos: "adj.", def: "Open to attack; easily injured physically and emotionally."},
    {word: "admonish", fos: "v.", def: "To warn."},
    {word: "aghast", fos: "adj.", def: "Struck with horror; shocked."},
    {word: "annihilate", fos: "v.", def: "To destroy completely; to reduce to utter ruin."},
    {word: "benefactor", fos: "n.", def: "A person who provides help, especially by giving money."},
    {word: "bestow", fos: "v.", def: "To give as an honor; to present as a gift."},
    {word: "devious", fos: "adj.", def: "Having many twists and turns; winding."},
    {word: "devoid", fos: "adj.", def: "Lacking; empty; entirely without."},
    {word: "heed", fos: "v.", def: "To pay attention to."},
    {word: "mortal", fos: "n.", def: "A human being, especially as contrasted with a god."},
    {word: "muse", fos: "v.", def: "To think about in a quiet, careful way."},
    {word: "pioneer", fos: "n.", def: "A person who goes before others and opens the way for them to follow."},
    {word: "plague", fos: "n.", def: "A deadly disease that spreads rapidly from person to person."},
    {word: "subside", fos: "v.", def: "To sink to a lower level."},
    {word: "unwitting", fos: "adj.", def: "Not done on purpose; unintended."},
    {word: "wrath", fos: "n.", def: "Forceful anger; fury."},
    {word: "acquire", fos: "v.", def: "To gain ownership of something; to get by one's own efforts or actions."},
    {word: "antagonize", fos: "v.", def: "To make an enemy of; to stir up anger or dislike."},
    {word: "competent", fos: "adj.", def: "Having the ability to do what is needed."},
    {word: "comprise", fos: "v.", def: "To form; to make up."},
    {word: "correspond", fos: "v.", def: "To match; to be equal to."},
    {word: "dilapidated", fos: "adj.", def: "In poor condition from neglect or age."},
    {word: "illustrious", fos: "adj.", def: "Very famous; outstanding."},
    {word: "incident", fos: "n.", def: "Something that happens in real life or in a story; an event, often of little importance."},
    {word: "inherit", fos: "v.", def: "To receive something from someone after that person's death."},
    {word: "latitude", fos: "n.", def: "The distance north or south of the equator, measured in degrees."},
    {word: "loath", fos: "adj.", def: "Unwilling; reluctant."},
    {word: "maintain", fos: "v.", def: "To declare something to be true."},
    {word: "renovate", fos: "v.", def: "To make like new again."},
    {word: "reprimand", fos: "v.", def: "To scold in a harsh or formal manner."},
    {word: "supervise", fos: "v.", def: "To direct or manage activities."},
    {word: "adequate", fos: "adj.", def: "Enough; sufficient."},
    {word: "administer", fos: "v.", def: "To manage or direct."},
    {word: "agitate", fos: "v.", def: "To disturb or upset."},
    {word: "capitulate", fos: "v.", def: "To give in; to surrender."},
    {word: "citrus", fos: "n.", def: "A fruit of the family that includes oranges, lemons, grapefruits, and limes."},
    {word: "disrupt", fos: "v.", def: "To break up the orderly course of."},
    {word: "hovel", fos: "n.", def: "An unpleasant, cramped, and dilapidated place to live."},
    {word: "illiterate", fos: "adj.", def: "Unable to read or write."},
    {word: "indifferent", fos: "adj.", def: "Not concerned about; not caring."},
    {word: "menial", fos: "adj.", def: "Of or relating to low-level, humble work."},
    {word: "permanent", fos: "adj.", def: "Lasting or expected to last for a long time."},
    {word: "respite", fos: "n.", def: "A period of rest; a pause."},
    {word: "strenuous", fos: "adj.", def: "Needing much effort; using a lot of energy."},
    {word: "toil", fos: "v.", def: "To work long and hard."},
    {word: "urgent", fos: "adj.", def: "Needing quick action or attention."},
    {word: "addict", fos: "n.", def: "A person with a very strong desire for something that is habit-forming and sometimes harmful."},
    {word: "aspire", fos: "v.", def: "To have a strong desire to get or do something; to seek."},
    {word: "bias", fos: "n.", def: "A preference that prevents one from being impartial; prejudice."},
    {word: "blatant", fos: "adj.", def: "Very obvious in an offensive or shameless way."},
    {word: "candid", fos: "adj.", def: "Expressed honestly and without holding back unpleasant truths."},
    {word: "confront", fos: "v.", def: "To stand up to; to face boldly."},
    {word: "debut", fos: "n.", def: "A first public appearance."},
    {word: "enroll", fos: "v.", def: "To sign up to become a member of some group or activity; to register."},
    {word: "fluster", fos: "v.", def: "To make nervous, embarrassed, or confused."},
    {word: "impunity", fos: "n.", def: "Freedom from being harmed or punished."},
    {word: "intensify", fos: "v.", def: "To increase, to strengthen or deepen."},
    {word: "intimidate", fos: "v.", def: "To frighten, especially by threatening someone."},
    {word: "obnoxious", fos: "adj.", def: "Very unpleasant; disgusting."},
    {word: "retort", fos: "v.", def: "To answer, especially in a quick or clever way."},
    {word: "stint", fos: "n.", def: "A period of time devoted to a job or some task."},
];
