export const words = [
    {word: "accustom", fos: "v.", def: "make (someone or something) accept something as normal or usual."},
    {word: "budge", fos: "v.", def: "make or cause to make the slightest movement."},
    {word: "burly", fos: "adj.", def: "(of a person) large and strong; heavily built."},
    {word: "jostle", fos: "v.", def: "push, elbow, or bump against (someone) roughly, typically in a crowd."},
    {word: "crave", fos: "v.", def: "feel a powerful desire for (something)."},
    {word: "cultivate", fos: "v.", def: "prepare and use (land) for crops or gardening."},
    {word: "ferocious", fos: "adj.", def: "savagely fierce, cruel, or violent."},
    {word: "puny", fos: "adj.", def: "small and weak."},
    {word: "despair", fos: "n.", def: "the complete loss or absence of hope."},
    {word: "gale", fos: "n.", def: "a very strong wind."},
    {word: "jubilation", fos: "n.", def: "a feeling of great happiness and triumph."},
    {word: "sever", fos: "v.", def: "divide by cutting or slicing, especially suddenly and forcibly."},
    {word: "crevice", fos: "n.", def: "a narrow opening or fissure, especially in a rock or wall."},
    {word: "foolhardy", fos: "adj.", def: "recklessly bold or rash."},
    {word: "terse", fos: "adj.", def: "sparing in the use of words; abrupt."},
    {word: "thwart", fos: "v.", def: "prevent (someone) from accomplishing something."},
    {word: "feeble", fos: "adj.", def: "lacking physical strength, especially as a result of age or illness."},
    {word: "frigid", fos: "adj.", def: "very cold in temperature."},
    {word: "huddle", fos: "v.", def: "crowd together; nestle closely."},
    {word: "solitary", fos: "adj.", def: "done or existing alone."},
    {word: "waddle", fos: "v.", def: "walk with short steps and a clumsy swaying motion."},
    {word: "banquet", fos: "n.", def: "an elaborate and formal meal for many people."},
    {word: "frivolous", fos: "adj.", def: "not having any serious purpose or value."},
    {word: "hew", fos: "v.", def: "chop or cut (something, especially wood or coal) with an axe, pick, or other tool."},
    {word: "soar", fos: "v.", def: "fly or rise high in the air."},
    {word: "unwieldy", fos: "adj.", def: "difficult to carry or move because of its size, shape, or weight."},
    {word: "yearn", fos: "v.", def: "have an intense feeling of longing for something, typically something that one has lost or been separated from."},
    {word: "exult", fos: "v.", def: "feel or show triumphant elation or jubilation."},
    {word: "nonchalant", fos: "adj.", def: "(of a person or manner) feeling or appearing casually calm and relaxed; not displaying anxiety, interest, or enthusiasm."},
    {word: "saunter", fos: "v.", def: "walk in a slow, relaxed manner, without hurry or effort."},
    {word: "stall", fos: "n.", def: "a stand, booth, or compartment for the sale of goods in a market or large covered area."},
    {word: "convalesce", fos: "v.", def: "recover one's health and strength over a period of time after an illness or operation."},
    {word: "exasperate", fos: "v.", def: "irritate and frustrate (someone) intensely."},
    {word: "tempest", fos: "n.", def: "a violent windy storm."},
    {word: "upbringing", fos: "n.", def: "the treatment and instruction received by a child from its parents throughout its childhood."},
    {word: "accommodate", fos: "v.", def: "(of physical space, especially a building) provide lodging or sufficient space for."},
    {word: "bask", fos: "v.", def: "lie exposed to warmth and light, typically from the sun, for relaxation and pleasure."},
    {word: "carcass", fos: "n.", def: "the dead body of an animal."},
    {word: "flail", fos: "v.", def: "wave or swing or cause to wave or swing wildly."},
    {word: "gorge", fos: "n.", def: "a narrow valley between hills or mountains, typically with steep rocky walls and a stream running through it."},
    {word: "morsel", fos: "n.", def: "a small piece or amount of food; a mouthful."},
    {word: "protrude", fos: "v.", def: "extend beyond or above a surface."},
    {word: "snout", fos: "n.", def: "the projecting nose and mouth of an animal, especially a mammal."},
    {word: "taunt", fos: "v.", def: "provoke or challenge (someone) with insulting remarks."},
    {word: "lurch", fos: "v.", def: "make an abrupt, unsteady, uncontrolled movement or series of movements; stagger."},
    {word: "petrify", fos: "v.", def: "make (someone) so frightened that they are unable to move."},
    {word: "sparse", fos: "adj.", def: "thinly dispersed or scattered."},
    {word: "topple", fos: "v.", def: "overbalance or become unsteady and fall slowly."},
    {word: "abdicate", fos: "v.", def: "(of a monarch) renounce one's throne."},
    {word: "bungle", fos: "v.", def: "carry out (a task) clumsily or incompetently."},
    {word: "hoist", fos: "v.", def: "raise (something) by means of ropes and pulleys."},
    {word: "jubilee", fos: "n.", def: "a special anniversary of an event, especially one celebrating twenty-five or fifty years of a reign or activity."},
    {word: "kin", fos: "n.", def: "one's family and relations."},
    {word: "erode", fos: "v.", def: "(of wind, water, or other natural agents) gradually wear away (soil, rock, or land)."},
    {word: "famine", fos: "n.", def: "extreme scarcity of food."},
    {word: "pasture", fos: "n.", def: "land covered with grass and other low plants suitable for grazing animals, especially cattle or sheep."},
    {word: "primitive", fos: "adj.", def: "relating to, denoting, or preserving the character of an early stage in the evolutionary or historical development of something."},
    {word: "teem", fos: "v.", def: "be full of or swarming with."},
    {word: "likeness", fos: "n.", def: "the fact or quality of being alike; resemblance."},
    {word: "meager", fos: "adj.", def: "(of something provided or available) lacking in quantity or quality."},
    {word: "somber", fos: "adj.", def: "dark or dull in color or tone; gloomy."},
    {word: "vow", fos: "n.", def: "a solemn promise."},
    {word: "dormant", fos: "adj.", def: "(of an animal) having normal physical functions suspended or slowed down for a period of time; in or as if in a deep sleep."},
    {word: "scald", fos: "v.", def: "injure with very hot liquid or steam."},
    {word: "stupendous", fos: "adj.", def: "extremely impressive."},
    {word: "ample", fos: "adj.", def: "enough or more than enough; plentiful."},
    {word: "cumbersome", fos: "adj.", def: "large or heavy and therefore difficult to carry or use; unwieldy."},
    {word: "indignant", fos: "adj.", def: "feeling or showing anger or annoyance at what is perceived as unfair treatment."},
    {word: "jest", fos: "n.", def: "a thing said or done for amusement; a joke."},
    {word: "mirth", fos: "n.", def: "amusement, especially as expressed in laughter."},
    {word: "clasp", fos: "v.", def: "grasp (something) tightly with one's hand."},
    {word: "conspicuous", fos: "adj.", def: "standing out so as to be clearly visible."},
    {word: "eloquent", fos: "adj.", def: "fluent or persuasive in speaking or writing."},
    {word: "lofty", fos: "adj.", def: "of imposing height."},
    {word: "pedestal", fos: "n.", def: "the base or support on which a statue, obelisk, or column is mounted."},
    {word: "persecute", fos: "v.", def: "subject (someone) to hostility and ill-treatment, especially because of their ethnicity, religion, or sexual orientation or their political beliefs."},
    {word: "arrogant", fos: "adj.", def: "having or revealing an exaggerated sense of one's own importance or abilities."},
    {word: "custody", fos: "n.", def: "the protective care or guardianship of someone or something."},
    {word: "segregate", fos: "v.", def: "set apart from the rest or from each other; isolate or divide."},
    {word: "arid", fos: "adj.", def: "(of land or a climate) having little or no rain; too dry or barren to support vegetation."},
    {word: "graze", fos: "v.", def: "(of cattle, sheep, etc.) eat grass in a field."},
    {word: "hectic", fos: "adj.", def: "full of incessant or frantic activity."},
    {word: "sanctuary", fos: "n.", def: "a place of refuge or safety."},
    {word: "splendor", fos: "n.", def: "magnificent and splendid appearance; grandeur."},
    {word: "squalor", fos: "n.", def: "the state of being extremely dirty and unpleasant, especially as a result of poverty or neglect."},
    {word: "aloft", fos: "adv.", def: "up in or into the air; overhead."},
    {word: "attain", fos: "v.", def: "succeed in achieving (something that one desires and has worked for)."},
    {word: "elude", fos: "v.", def: "evade or escape from (a danger, enemy, or pursuer), typically in a skillful or cunning way."},
    {word: "jeopardy", fos: "n.", def: "danger of loss, harm, or failure."},
    {word: "moor", fos: "v.", def: "make fast (a boat) by attaching it by cable or rope to the shore or to an anchor."},
    {word: "swivel", fos: "n.", def: "a coupling between two parts enabling one to revolve without turning the other."},
    {word: "antic", fos: "adj.", def: "grotesque or bizarre."},
    {word: "attire", fos: "n.", def: "clothes, especially fine or formal ones."},
    {word: "captivate", fos: "v.", def: "attract and hold the interest and attention of; charm."},
    {word: "deft", fos: "adj.", def: "neatly skillful and quick in one's movements."},
    {word: "eclipse", fos: "n.", def: "an obscuring of the light from one celestial body by the passage of another between it and the observer or between it and its source of illumination."},
    {word: "innate", fos: "adj.", def: "inborn; natural."},
    {word: "inscribe", fos: "v.", def: "write or carve (words or symbols) on something, especially as a formal or permanent record."},
    {word: "shroud", fos: "n.", def: "a length of cloth or an enveloping garment in which a dead person is wrapped for burial."},
    {word: "stifle", fos: "v.", def: "make (someone) unable to breathe properly; suffocate."},
    {word: "tentative", fos: "adj.", def: "not certain or fixed; provisional."},
    {word: "tranquil", fos: "adj.", def: "free from disturbance; calm."},
    {word: "apparel", fos: "n.", def: "clothing."},
    {word: "sheathe", fos: "v.", def: "put (a weapon such as a knife or sword) into a sheath."},
    {word: "shed", fos: "n.", def: "a simple roofed structure, typically made of wood or metal, used as a storage space, a shelter for animals, or a workshop."},
    {word: "hardy", fos: "adj.", def: "robust; capable of enduring difficult conditions."},
    {word: "ravenous", fos: "adj.", def: "extremely hungry."},
    {word: "stampede", fos: "n.", def: "a sudden panicked rush of a number of horses, cattle, or other animals."},
    {word: "captive", fos: "n.", def: "a person who has been taken prisoner or an animal that has been confined."},
    {word: "expanse", fos: "n.", def: "an area of something, typically land or sea, presenting a wide continuous surface."},
    {word: "inept", fos: "adj.", def: "having or showing no skill; clumsy."},
    {word: "skirmish", fos: "n.", def: "an episode of irregular or unpremeditated fighting, especially between small or outlying parts of armies or fleets."},
    {word: "aggravate", fos: "v.", def: "make (a problem, injury, or offense) worse or more serious."},
    {word: "extravagant", fos: "adj.", def: "lacking restraint in spending money or using resources."},
    {word: "frugal", fos: "adj.", def: "sparing or economical with regard to money or food."},
    {word: "peril", fos: "n.", def: "serious and immediate danger."},
    {word: "brisk", fos: "adj.", def: "active, fast, and energetic."},
    {word: "err", fos: "v.", def: "be mistaken or incorrect; make a mistake."},
    {word: "fad", fos: "n.", def: "an intense and widely shared enthusiasm for something, especially one that is short-lived and without basis in the object's qualities; a craze."},
    {word: "gripe", fos: "v.", def: "complain about something in a persistent, irritating way."},
    {word: "knack", fos: "n.", def: "an acquired or natural skill at performing a task."},
    {word: "fanciful", fos: "adj.", def: "overly imaginative and unrealistic."},
    {word: "grudge", fos: "n.", def: "a persistent feeling of ill will or resentment resulting from a past insult or injury."},
    {word: "resolute", fos: "adj.", def: "admirably purposeful, determined, and unwavering."},
    {word: "sneer", fos: "n.", def: "a contemptuous or mocking smile, remark, or tone."},
    {word: "unruly", fos: "adj.", def: "disorderly and disruptive and not amenable to discipline or control."},
    {word: "adversary", fos: "n.", def: "one's opponent in a contest, conflict, or dispute."},
    {word: "baffle", fos: "v.", def: "totally bewilder or perplex."},
    {word: "colossal", fos: "adj.", def: "extremely large."},
    {word: "haul", fos: "v.", def: "(of a person) pull or drag with effort or force."},
    {word: "rejoice", fos: "v.", def: "feel or show great joy or delight."},
    {word: "scoff", fos: "v.", def: "speak to someone or about something in a scornfully derisive or mocking way."},
    {word: "sinister", fos: "adj.", def: "giving the impression that something harmful or evil is happening or will happen."},
    {word: "victor", fos: "n.", def: "a person who defeats an enemy or opponent in a battle, game, or other competition."},
    {word: "woe", fos: "n.", def: "great sorrow or distress (often used hyperbolically)."},
    {word: "gait", fos: "n.", def: "a person's manner of walking."},
    {word: "oblivious", fos: "adj.", def: "not aware of or not concerned about what is happening around one."},
    {word: "outmoded", fos: "adj.", def: "old-fashioned."},
    {word: "prominent", fos: "adj.", def: "important; famous."},
    {word: "quench", fos: "v.", def: "satisfy (one's thirst) by drinking."},
    {word: "rigor", fos: "n.", def: "a sudden feeling of cold with shivering accompanied by a rise in temperature, often with copious sweating, especially at the onset or height of a fever."},
    {word: "sear", fos: "v.", def: "burn or scorch the surface of (something) with a sudden, intense heat."},
    {word: "wend", fos: "v.", def: "go in a specified direction, typically slowly or by an indirect route."},
    {word: "benevolent", fos: "adj.", def: "kind and with positive intentions."},
    {word: "discreet", fos: "adj.", def: "careful and circumspect in one's speech or actions, especially in order to avoid causing offense or to gain an advantage."},
    {word: "engross", fos: "v.", def: "absorb all the attention or interest of."},
    {word: "intrigue", fos: "v.", def: "arouse the curiosity or interest of; fascinate."},
    {word: "marvel", fos: "v.", def: "be filled with wonder or astonishment."},
    {word: "relinquish", fos: "v.", def: "cease to keep or claim (something); give up."},
    {word: "vanquish", fos: "v.", def: "defeat thoroughly."},
    {word: "apprehensive", fos: "adj.", def: "anxious or fearful that something bad or unpleasant will happen."},
    {word: "envelop", fos: "v.", def: "wrap up, cover, or surround completely."},
    {word: "fatality", fos: "n.", def: "an occurrence of death by accident, in war, or from disease."},
    {word: "lull", fos: "v.", def: "calm or send to sleep, typically with soothing sounds or movements."},
    {word: "placid", fos: "adj.", def: "(of a person or animal) not easily upset or excited."},
    {word: "stern", fos: "adj.", def: "(of a person or their manner) serious and unrelenting, especially in asserting authority or exercising discipline."},
    {word: "treacherous", fos: "adj.", def: "guilty of or involving betrayal or deception."},
    {word: "elated", fos: "adj.", def: "ecstatically happy."},
    {word: "leeway", fos: "n.", def: "the amount of freedom to move or act that is available."},
    {word: "ooze", fos: "v.", def: "(of a fluid) slowly trickle or seep out of something; flow in a very gradual way."},
    {word: "pathetic", fos: "adj.", def: "arousing pity, especially through vulnerability or sadness."},
    {word: "scour", fos: "v.", def: "clean or brighten the surface of (something) by rubbing it hard, typically with an abrasive or detergent."},
    {word: "anguish", fos: "n.", def: "severe mental or physical pain or suffering."},
    {word: "commend", fos: "v.", def: "praise formally or officially."},
    {word: "cordial", fos: "adj.", def: "warm and friendly."},
    {word: "dissent", fos: "n.", def: "the holding or expression of opinions at variance with those commonly or officially held."},
    {word: "earnest", fos: "adj.", def: "resulting from or showing sincere and intense conviction."},
    {word: "elicit", fos: "v.", def: "evoke or draw out (a response, answer, or fact) from someone in reaction to one's own actions or questions."},
    {word: "exhilaration", fos: "n.", def: "a feeling of excitement, happiness, or elation."},
    {word: "skeptic", fos: "n.", def: "a person inclined to question or doubt accepted opinions."},
    {word: "clammy", fos: "adj.", def: "unpleasantly damp and sticky or slimy to touch."},
    {word: "fragrant", fos: "adj.", def: "having a pleasant or sweet smell."},
    {word: "furnish", fos: "v.", def: "provide (a house or room) with furniture and fittings."},
    {word: "haven", fos: "n.", def: "a place of safety or refuge."},
    {word: "retaliate", fos: "v.", def: "make an attack or assault in return for a similar attack."},
    {word: "stench", fos: "n.", def: "a strong and very unpleasant smell."},
    {word: "strew", fos: "v.", def: "scatter or spread (things) untidily over a surface or area."},
    {word: "vicinity", fos: "n.", def: "the area near or surrounding a particular place."},
    {word: "bluster", fos: "v.", def: "talk in a loud, aggressive, or indignant way with little effect."},
    {word: "dwell", fos: "v.", def: "live in or at a specified place."},
    {word: "garment", fos: "n.", def: "an item of clothing."},
    {word: "infest", fos: "v.", def: "(of insects or animals) be present (in a place or site) in large numbers, typically so as to cause damage or disease."},
    {word: "paltry", fos: "adj.", def: "(of an amount) small or meager."},
    {word: "peculiar", fos: "adj.", def: "strange or odd; unusual."},
    {word: "rash", fos: "adj.", def: "displaying or proceeding from a lack of careful consideration of the possible consequences of an action."},
    {word: "vat", fos: "n.", def: "a large tank or tub used to hold liquid, especially in industry."},
    {word: "taper", fos: "v.", def: "diminish or reduce in thickness toward one end."},
];
