export const words = [
    {word: "acrid", fos: "adj.", def: "Sharp, irritating, or bitter to the sense of taste or smell."},
    {word: "casualty", fos: "n.", def: "A person killed or injured in a war or accident."},
    {word: "congested", fos: "adj.", def: "Overcrowded; filled too full."},
    {word: "cope", fos: "v.", def: "To manage problems or difficulties successfully."},
    {word: "headlong", fos: "adj.", def: "With great speed or force; reckless."},
    {word: "hurtle", fos: "v.", def: "To move with great force and speed."},
    {word: "impede", fos: "v.", def: "To get in the way of; to interfere with the movement of."},
    {word: "inevitable", fos: "adj.", def: "Bound to happen; unavoidable."},
    {word: "initiate", fos: "v.", def: "To put into effect; to bring into use."},
    {word: "irate", fos: "adj.", def: "Very angry; furious."},
    {word: "lax", fos: "adj.", def: "Not strictly enforced; undemanding; careless."},
    {word: "negligent", fos: "adj.", def: "Failing to take proper care of or to give proper attention to."},
    {word: "smolder", fos: "v.", def: "To burn slowly without bursting into flames."},
    {word: "stringent", fos: "adj.", def: "Strict; severe."},
    {word: "throng", fos: "n.", def: "A large number of people gathered together; a crowd."},
    {word: "dumbfound", fos: "v.", def: "To make speechless with amazement."},
    {word: "ensue", fos: "v.", def: "To follow; to come as a result of or at a later time."},
    {word: "era", fos: "n.", def: "A particular period in history."},
    {word: "flourish", fos: "v.", def: "To thrive or prosper."},
    {word: "garrison", fos: "n.", def: "Soldiers stationed in a place to protect it."},
    {word: "grievous", fos: "adj.", def: "Causing grief or pain; hard to bear."},
    {word: "hoard", fos: "v.", def: "To save and put away, especially secretly."},
    {word: "inundate", fos: "v.", def: "To cover, as with water from a flood."},
    {word: "invincible", fos: "adj.", def: "Impossible to defeat."},
    {word: "nomad", fos: "n.", def: "A member of a group that settles briefly in one place and then moves on to another."},
    {word: "placate", fos: "v.", def: "To stop from being angry; to calm."},
    {word: "principal", fos: "adj.", def: "Most important."},
    {word: "recede", fos: "v.", def: "To move back or to drop to a lower level."},
    {word: "ruthless", fos: "adj.", def: "Showing no mercy; pitiless."},
    {word: "sacrifice", fos: "n.", def: "Something given up for the sake of another."},
    {word: "aquatic", fos: "adj.", def: "Growing or living in or on water."},
    {word: "assert", fos: "v.", def: "To say firmly; to declare."},
    {word: "avert", fos: "v.", def: "To turn away."},
    {word: "bleak", fos: "adj.", def: "Without much hope."},
    {word: "blithe", fos: "adj.", def: "Cheerful; carefree."},
    {word: "docile", fos: "adj.", def: "Well behaved; easy to handle."},
    {word: "dwindle", fos: "v.", def: "To continue becoming less; to grow smaller in number or amount."},
    {word: "lethal", fos: "adj.", def: "Causing, or capable of, death."},
    {word: "monitor", fos: "v.", def: "To watch closely and frequently; to observe and make note."},
    {word: "mutilate", fos: "v.", def: "To hurt or damage by cutting into, cutting off, or cutting out."},
    {word: "nimble", fos: "adj.", def: "Able to move quickly and easily."},
    {word: "plight", fos: "n.", def: "A difficult or dangerous condition or situation."},
    {word: "ponderous", fos: "adj.", def: "Heavy and slow moving."},
    {word: "verge", fos: "n.", def: "An edge, border, or brink."},
    {word: "vigilant", fos: "adj.", def: "Watchful; ready for danger."}
];
